Liele|Re: WHAT UP GIRL!!!!|03/23/04 - 15:15:21|yes i can lol|1080076510|1
Tumeddar|Re: fuck this shit|03/23/04 - 15:06:33|aye i just got in|1080075984|1
Liele|Re: WHAT UP GIRL!!!!|03/23/04 - 15:03:58|lmao|1080075828|1
Tumeddar|Re: fuck this shit|03/23/04 - 15:02:57|kk will do can you get in the chat chan?|1080075763|1|1
Tumeddar|Re: fuck this shit|03/23/04 - 14:59:04|im not really sure what series i use lol i just know that i use gforce hehe... not a big comp person *needs to learn more*|1080075479|1
Liele|Re: WHAT UP GIRL!!!!|03/23/04 - 14:58:07|good to hear that<br>couldn't bare picking on ray without ya|1080075461|1
admin|Chat room|03/23/04 - 14:56:48|Chatroom is now up and running!!!|1080075408|1
Liele|Re: WHAT UP GIRL!!!!|03/23/04 - 14:54:46|yeah hope so =/|1080075270|1
Tumeddar|Re: fuck this shit|03/23/04 - 14:53:42|think i have msn well i know its not aol thats all LOL....were can i get a new vid card...lmao and is it easy to install by myself??|1080075160|1
Liele|Re: WHAT UP GIRL!!!!|03/23/04 - 14:50:42|booo don't say that you have a wedding to attend to hehe<br>|1080075018|1
Tumeddar|Re: fuck this shit|03/23/04 - 14:48:51|you need new drivers to play?...i have Gforce4 or something and it told me i needed better also &gt;&lt; thanks for the gratz forgot you were on last night i was SOOOO drunk hahhaa|1080074761|1
Liele|Re: WHAT UP GIRL!!!!|03/23/04 - 14:48:10|hehe i know i already had directx9 lol|1080074870|1
Liele|Re: WHAT UP GIRL!!!!|03/23/04 - 14:44:38|no not you unless you want to be it lol|1080074665|1
Tumeddar|Re: fuck this shit|03/23/04 - 14:41:48|ouch ok u win that blows BIG ONE!<br><br>woot btw got Nd3 last night woohoo|1080074466|1
