test|test|03/25/04 - 10:42:14|another test messages sorry guys|1080232935|1
admin|New IM System|03/24/04 - 16:17:12|Added in a new IM system. Sorry about the test messages if you got them! [grin]|1080166632
admin|New Features added!!|03/24/04 - 14:54:39|New to the website is:<br><br>Journal: This is private. Only you can see this so you can log any info you need too here.<br><br>Edit My Menu: This feature you can add links to the menu bar for sites you may like to visit offten. Thease links will only be displayed to you.|1080161680
admin|Sticky Forms fixed|03/24/04 - 10:27:35|Everyone should now be abel to post replys to the sticky forms. If you still have the problem please let me know.|1080145655
Lumi|Welcome To Freefire!!|03/24/04 - 01:16:25|Welcome to Freefire. Please feel free to look around, Use the forms and messaging system. As of right now your account is set as friend. Once you are verified a a member of Freefire your account will be changed.||1
