Ajia|Buddy List|05/02/04 - 20:41:58|User Ajia. has added you to there Buddy List. View Profile of <a href=http://www.eqguilded.com/freefire/cgi-bin/index.cgi?action=viewprofile&username=Ajia>Ajia</a>|1083548518
test|test|03/25/04 - 10:42:14|another test messages sorry guys|1080232934
admin|New IM System|03/24/04 - 16:17:12|Added in a new IM system. Sorry about the test messages if you got them! [grin]|1080166632
admin|test|03/24/04 - 16:13:20|testing|1080166400
admin|New Features added!!|03/24/04 - 14:54:39|New to the website is:<br><br>Journal: This is private. Only you can see this so you can log any info you need too here.<br><br>Edit My Menu: This feature you can add links to the menu bar for sites you may like to visit offten. Thease links will only be displayed to you.|1080161680
admin|Sticky Forms fixed|03/24/04 - 10:27:35|Everyone should now be abel to post replys to the sticky forms. If you still have the problem please let me know.|1080145655
admin|Chat room|03/23/04 - 14:56:48|Chatroom is now up and running!!!|1080075408
admin|=\|03/23/04 - 14:32:02|Coralhunt is going to get it!! You just wate and see!!|1080073922
Coralhunt|all, |03/23/04 - 14:07:03|is anyone deleting posts, or is any admin moving posts to dump folder?|1080072423
Coralhunt|OMG HELP THE GNOME|03/23/04 - 14:03:38|His safty rope broke, &nbsp;and he fell into the system. &nbsp;Anyone able to summon short people? &nbsp;<br><br>|1080072218
Killaana|cya's later, |03/23/04 - 13:59:47|well actually in like 12 hours will be back home off duty...going to have dinner with liele, be there in like 20 to 30 min...night all|1080071987
Coralhunt|Gnome, on the job|03/23/04 - 13:57:43|Gnome is out digging through the system, &nbsp;please ignore the sparks and frayed wires as he is really going to town.<br><br>|1080071863
Coralhunt|posts|03/23/04 - 13:55:17|Seems we have a posting problem on repling to stickies that we are tracking down. &nbsp;<br><br>Also, important post, please keep a copy of them just in case there is a sneaky server issue happening. &nbsp;No panicks yet<br>|1080071717
Killaana|woot|03/23/04 - 13:35:07|woot look at all these members online, we need a chat room lol, this is a site wide IM btw, so going to all online people|1080070507
admin|Forms Not allowing you to post!!|03/23/04 - 13:12:31|If you have this problem with not being able to post a reply to sticky threads please send me a IM with the thread you wanted to post and the time so I can try and track down what is causing this to happen.<br><br>It seems to only be messing up on sticky posts. Please let me know if you have this problem.|1080069151
