scottro|Re: Ola sweety|05/26/04 - 13:50:23|I'm fine. &nbsp;=) &nbsp;Im sorry for the outburst. &nbsp;I realize i like to go faster than others and sometimes i need to be riegned in. &nbsp;I am just impatient at times. &nbsp;I think you are a good guild member and have been super nice to me. &nbsp;I am glad it was a misunderstanding.|1085596960|aicon2|1
klassy|Re: VSR|05/25/04 - 15:14:44|We will get em then!<br><br>Hugs|1085516070|aicon2|1
klassy|VSR|05/25/04 - 07:49:41|VSR should be up again today at 12pm or so.|1085489348|aicon2|1
Killaana|Re: ...|05/17/04 - 09:47:15|hugs and kisses[imxkiss]|1084805210|icon7|1
Mank|Re: Forum post|05/12/04 - 21:22:47|no worries. i jumped the gun &nbsp;there &nbsp; &nbsp;and &nbsp; i am &nbsp;sorry &nbsp; also [imxlove][imxgrin][imxlol]|1084414776|aicon2|1
