#!/usr/bin/perl

#####################################
##                                 ##
##             REMOTE              ##
##  CoppyRight Byron Chilton 2000  ##
##       http://www.d0tt.com       ##
##                                 ##
##      DO NOT EDIT THIS FILE      ##
##                                 ##
#####################################

require "config.pl";

  read(STDIN, $buffer, $ENV{'CONTENT_LENGTH'});
  if (length($buffer) < 5) {
    $buffer = $ENV{QUERY_STRING};
  }
 
  @pairs = split(/&/, $buffer);
  foreach $pair (@pairs) {
    ($name, $value) = split(/=/, $pair);

    $value =~ tr/+/ /;
    $value =~ s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/eg;
    $value =~ s/[\;\|\\ ]/ /ig;
    $INPUT{$name} = $value;
}
if ($INPUT{'u'} ne "") {
open (FILE, "$data_path/$INPUT{'u'}.mem");
flock (FILE, 2);
$name = <FILE>;
chop ($name);
$cryptpass = <FILE>;
chop ($cryptpass);
$mail = <FILE>;
chop ($mail);
$url = <FILE>;
chop ($url);
$site_title = <FILE>;
chop ($site_title);
flock (FILE, 8);
close(FILE);

if ($name ne "") {

if ($INPUT{'s'} eq "") { 
$INPUT{'s'} = "1";
 }
if ($INPUT{'w'} eq "") { 
$INPUT{'w'} = "15";
 }
if ($INPUT{'h'} eq "") { 
$INPUT{'h'} = "15";
 }

($sec,$min,$hour,$day,$month,$year,$day2) = (localtime(time))[0,1,2,3,4,5,6];
if ($sec < 10) { $sec = "0$sec"; }
if ($min < 10) { $min = "0$min"; }
if ($hour < 10) { $hour = "0$hour"; }
if ($hour >= 12) { $ex = "p"; }
else { $ex = "a"; }
if ($hour == 0) { $hour = 12; }
if ($hour > 12) { $hour -= 12; }
@hour = split(//,$hour);      
@min = split(//,$min);   
@sec = split(//,$sec);     
$total_width = $INPUT{'w'} * 9;  
open(FLY,">$data_path\/clock_temp.txt");
print FLY "new\n";
print FLY "size $total_width,$INPUT{'h'}\n";
$insert_width = "0";
foreach $hour (@hour) {
    print FLY "copy $insert_width,0,-1,-1,-1,-1,$image_directory/$INPUT{'s'}/$hour.gif\n";
    $insert_width = $insert_width + $INPUT{'w'};
}
print FLY "copy $insert_width,0,-1,-1,-1,-1,$image_directory/$INPUT{'s'}/-.gif\n";
$insert_width = $insert_width + $INPUT{'w'};
foreach $min (@min) {
    print FLY "copy $insert_width,0,-1,-1,-1,-1,$image_directory/$INPUT{'s'}/$min.gif\n";
    $insert_width = $insert_width + $INPUT{'w'};
}
print FLY "copy $insert_width,0,-1,-1,-1,-1,$image_directory/$INPUT{'s'}/-.gif\n";
$insert_width = $insert_width + $INPUT{'w'};
foreach $sec (@sec) {
    print FLY "copy $insert_width,0,-1,-1,-1,-1,$image_directory/$INPUT{'s'}/$sec.gif\n";
    $insert_width = $insert_width + $INPUT{'w'};
}
print FLY "copy $insert_width,0,-1,-1,-1,-1,$image_directory/$INPUT{'s'}/$ex.gif\n";
$insert_width = $insert_width + $INPUT{'w'};
close(FLY);
print "Content-type: image/gif\n\n";
print `$flyprog -i $data_path\/clock_temp.txt`;
unlink("$data_path\/clock_temp.txt");

}
}