#!/usr/bin/perl

#####################################
##                                 ##
##             REMOTE              ##
##  CoppyRight Byron Chilton 2000  ##
##       http://www.d0tt.com       ##
##                                 ##
##      DO NOT EDIT THIS FILE      ##
##                                 ##
#####################################

require "config.pl";

  read(STDIN, $buffer, $ENV{'CONTENT_LENGTH'});
  if (length($buffer) < 5) {
    $buffer = $ENV{QUERY_STRING};
  }
 
  @pairs = split(/&/, $buffer);
  foreach $pair (@pairs) {
    ($name, $value) = split(/=/, $pair);

    $value =~ tr/+/ /;
    $value =~ s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/eg;
    $value =~ s/[\;\|\\ ]/ /ig;
    $INPUT{$name} = $value;
}
if ($INPUT{'u'}) {
open (FILE, "$data_path/$INPUT{'u'}.mem");
flock (FILE, 2);
$name = <FILE>;
chop ($name);
$cryptpass = <FILE>;
chop ($cryptpass);
$mail = <FILE>;
chop ($mail);
$url = <FILE>;
chop ($url);
$site_title = <FILE>;
chop ($site_title);
flock (FILE, 8);
close(FILE);

if ($name eq "") { 
$alow = "no";
}
else {

open (GETDATA, "$data_path/$INPUT{'u'}.rid");
@Data = <GETDATA>;
close GETDATA;

srand(time ^ $$);
$number = rand(@Data);
$image = @Data[$number];

print "Location: $image\n\n";

}
}