#!/usr/bin/perl

####################################
##                                ##
##            REMOTE              ##
##  CopyRight Byron Chilton 2000  ##
##      http://www.d0tt.com       ##
##                                ##
##     DO NOT EDIT THIS FILE      ##
##                                ##
####################################

require "config.pl";


  read(STDIN, $buffer, $ENV{'CONTENT_LENGTH'});
  if (length($buffer) < 5) {
    $buffer = $ENV{QUERY_STRING};
  }
 
  @pairs = split(/&/, $buffer);
  foreach $pair (@pairs) {
    ($name, $value) = split(/=/, $pair);

    $value =~ tr/+/ /;
    $value =~ s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/eg;
    $value =~ s/[\;\|\\ ]/ /ig;
    push(@values,$value); push(@names,$name);   
    $INPUT{$name} = $value;
  }

if ($INPUT{'u'} ne "") {
open (FILE, "$data_path/$INPUT{'u'}.mem");
flock (FILE, 2);
$name = <FILE>;
chop ($name);
$cryptpass = <FILE>;
chop ($cryptpass);
$mail = <FILE>;
chop ($mail);
$url = <FILE>;
chop ($url);
$site_title = <FILE>;
chop ($site_title);
flock (FILE, 8);
close(FILE);

if ($name eq "") {
print "Content-type: text/html\n\n";
print "<CENTER><B>Username Error!! The username $INPUT{'user'} was not found!!</B></CENTER>";
}
else {

$mailto=$INPUT{'to'};
$redir=$INPUT{'redir'};
  $redir="$siteurl" unless ($redir); 
$subject=$INPUT{'subject'};
$name=$INPUT{'name'};
$themail=$INPUT{'email'};


@keys=(keys %INPUT);
@keys=@names;

open (MAIL, "| $mailprog -t -oi") || die "Can't open $mailprog";
print MAIL "To: $mailto\n";
print MAIL "Reply-to: $themail\n";
print MAIL "From: $themail\n";
print MAIL "Subject: $subject\n";
print MAIL "Message from $name\n\n";
foreach $k (@keys) {
if ($k eq "email") { print MAIL ""; }
elsif ($k eq "u") { print MAIL ""; }
elsif ($k eq "subject") { print MAIL ""; }
elsif ($k eq "redir") { print MAIL ""; }
elsif ($k eq "to") { print MAIL ""; }
else { print MAIL "$k: $INPUT{$k}\n"; }
}
print MAIL "\n\n\n";
print MAIL "E-Mail Form provided by $home_page";
close (MAIL);
print "Location: $redir\n\n";

exit;
}
}
else {
print "Content-type: text/html\n\n";
print "<CENTER><B>No username enterd!! Please return to the main page and remake your code</B></CENTER>";
}