#!/usr/bin/perl

####################################
##                                ##
##            REMOTE              ##
##  CopyRight Byron Chilton 2000  ##
##      http://www.d0tt.com       ##
##                                ##
##     DO NOT EDIT THIS FILE      ##
##                                ##
####################################

require "config.pl";


  read(STDIN, $buffer, $ENV{'CONTENT_LENGTH'});
  if (length($buffer) < 5) {
    $buffer = $ENV{QUERY_STRING};
  }
 
  @pairs = split(/&/, $buffer);
  foreach $pair (@pairs) {
    ($name, $value) = split(/=/, $pair);

    $value =~ tr/+/ /;
    $value =~ s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/eg;
    $value =~ s/[\;\|\\ ]/ /ig;
    push(@values,$value); push(@names,$name);   
    $INPUT{$name} = $value;
  }

print "Content-type: text/html\n\n";

if($INPUT{'u'} eq "") {
print "Content-type: text/html\n\n";
print <<"HTML";
No username
HTML
}

else {
open (FILE, "$data_path/$INPUT{'u'}.mem");
flock (FILE, 2);
$name = <FILE>;
chop ($name);
$cryptpass = <FILE>;
chop ($cryptpass);
$mail = <FILE>;
chop ($mail);
$url = <FILE>;
chop ($url);
$site_title = <FILE>;
chop ($site_title);
flock (FILE, 8);
close(FILE);

if ($name eq "") { 
print "<CENTER><B>Username Error!! The username $INPUT{'user'} was not found!!</B></CENTER>";
}

else {
open (FILE, "$data_path/$INPUT{'u'}.wpd");
flock (FILE, 2);
$title = <FILE>;
chop ($title);
$qust = <FILE>;
chop ($qust);
$idem1 = <FILE>;
chop ($idem1);
$idem2 = <FILE>;
chop ($idem2);
$idem3 = <FILE>;
chop ($idem3);
$idem4 = <FILE>;
chop ($idem4);
$value1 = <FILE>;
chop ($value1);
$value2 = <FILE>;
chop ($value2);
$value3 = <FILE>;
chop ($value3);
$value4 = <FILE>;
chop ($value4);
flock (FILE, 8);
close(FILE);
if ($title eq "") { 
print "<CENTER><B>Poll Error!! This WebPoll is misconfigered!!</B></CENTER>";
}

else {
if($INPUT{'idem'} eq "1") {
$value1++
}
if($INPUT{'idem'} eq "2") {
$value2++
}
if($INPUT{'idem'} eq "3") {
$value3++
}
if($INPUT{'idem'} eq "4") {
$value4++
}

open(cnt, ">$data_path/$INPUT{'u'}.wpd");
print cnt "$title\n";
print cnt "$qust\n";
print cnt "$idem1\n";
print cnt "$idem2\n";
print cnt "$idem3\n";
print cnt "$idem4\n";
print cnt "$value1\n";
print cnt "$value2\n";
print cnt "$value3\n";
print cnt "$value4\n";
close(cnt);

print <<"HTML";
<CENTER><TABLE BORDER="0" CELLPADDING="2" ALIGN="Center">
<TR><TD COLSPAN=2><P ALIGN=Center>
<B>$title WebPoll</B></TD>
</TR>
<TR><TD COLSPAN=2>$qust</TD>
<TR><TD>$idem1</TD><TD>$value1 Votes</TD>
</TR><TR><TD>$idem2</TD><TD>$value2 Votes</TD>
</TR><TR><TD>$idem3</TD><TD>$value3 Votes</TD>
</TR><TR><TD>$idem4</TD><TD>$value4 Votes</TD>
</TR><TR><TD COLSPAN=2><P ALIGN=Center>
<A HREF="$url">Back To main site</A></TD>
</TR><TR><TD COLSPAN=2><P ALIGN=Center>
<A HREF="$home_page">Get your own FREE WebPoll</A></TD>
</TR></TABLE></CENTER>
HTML
}
}
}