#!/usr/bin/perl

####################################
##                                ##
##            REMOTE              ##
##  CopyRight Byron Chilton 2000  ##
##      http://www.d0tt.com       ##
##                                ##
##     DO NOT EDIT THIS FILE      ##
##                                ##
####################################

require "config.pl";

  read(STDIN, $buffer, $ENV{'CONTENT_LENGTH'});
  if (length($buffer) < 5) {
    $buffer = $ENV{QUERY_STRING};
  }
 
  @pairs = split(/&/, $buffer);
  foreach $pair (@pairs) {
    ($name, $value) = split(/=/, $pair);

    $value =~ tr/+/ /;
    $value =~ s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/eg;
    $value =~ s/[\;\|\\ ]/ /ig;
    $INPUT{$name} = $value;
}

print "Content-type: text/html\n\n";
&header;

  if($ENV{QUERY_STRING} eq "add") { &add_form }
  elsif($ENV{QUERY_STRING} eq "admin") { &admin_login }
  elsif($INPUT{'a'} eq "login") { &val_login }
  elsif($INPUT{'a'} eq "add") { &valadate_add }
  else { &login_form }

sub valadate_add {
if ($INPUT{'user'} eq "") {
print "<CENTER><B>No Username was entered</B></CENTER>";
}
elsif ($INPUT{'pass'} eq "") {
print "<CENTER><B>No Password was entered</B></CENTER>";
}
elsif ($INPUT{'mail'} eq "") {
print "<CENTER><B>No E-Mail was entered</B></CENTER>";
}
elsif ($INPUT{'url'} eq "") {
print "<CENTER><B>No WebPage URL was entered</B></CENTER>";
}
elsif ($INPUT{'url'} eq "http://") {
print "<CENTER><B>No WebPage URL was entered</B></CENTER>";
}
elsif ($INPUT{'site_title'} eq "") {
print "<CENTER><B>No Site Title was entered</B></CENTER>";
}
else {
open (FILE, "$data_path/$INPUT{'user'}.mem");
flock (FILE, 2);
$name = <FILE>;
chop ($name);
$cryptpass = <FILE>;
chop ($cryptpass);
$mail = <FILE>;
chop ($mail);
$url = <FILE>;
chop ($url);
$site_title = <FILE>;
chop ($site_title);
flock (FILE, 8);
close(FILE);

if ($name eq "") { &add_member }
else { print "<CENTER><B>Sorry, The username \"$INPUT{'user'}\" is already taken!</B></CENTER>"; }
}
}

sub add_member {
open(data, ">>mem.data");
@data=<data>;
close(data);
open(data, ">>mem.data");
foreach $line (@data){
print data "$line";
}
print data "$INPUT{'user'}\n";
close(data);

$cryptpass = crypt($INPUT{'pass'}, "aa");

open(cnt, ">$data_path/$INPUT{'user'}.mem");
print cnt "$INPUT{'user'}\n";
print cnt "$cryptpass\n";
print cnt "$INPUT{'mail'}\n";
print cnt "$INPUT{'url'}\n";
print cnt "$INPUT{'site_title'}\n";
close(cnt);

&thank_you;

open (MAIL, "| $mailprog -t -oi") || die "Can't open $mailprog";
print MAIL "To: $INPUT{'mail'}\n";
print MAIL "Reply-to: $email\n";
print MAIL "From: $email\n";
print MAIL "Subject: Thank you for joining $site_name\n";
print MAIL "Thank you for joining $site_name\n\n";
print MAIL "Your member data is as follows:\n";
print MAIL "Username: $INPUT{'user'}\n";
print MAIL "Password: $INPUT{'pass'}\n";
print MAIL "E-Mail: $INPUT{'mail'}\n";
print MAIL "URL: $INPUT{'url'}\n";
print MAIL "Site Title: $INPUT{'site_title'}\n\n";
print MAIL "It is recommended that you print this E-mail\n\n";
print MAIL "To login to your acount go to:\n";
print MAIL "$home_page\n\n";
print MAIL "Thank you\n";
print MAIL "Webmaster\n";
print MAIL "$site_name\n";
}

sub val_login {
if ($INPUT{'user'} eq "") {
print "<CENTER><B>No Username was entered</B></CENTER>";
}
elsif ($INPUT{'pass'} eq "") {
print "<CENTER><B>No Password was entered</B></CENTER>";
}
else {
open (FILE, "$data_path/$INPUT{'user'}.mem");
flock (FILE, 2);
$name = <FILE>;
chop ($name);
$cryptpass = <FILE>;
chop ($cryptpass);
$mail = <FILE>;
chop ($mail);
$url = <FILE>;
chop ($url);
$site_title = <FILE>;
chop ($site_title);
flock (FILE, 8);
close(FILE);

if ($name eq "") { print "<CENTER><B>Sorry, The username \"$INPUT{'user'}\" Wasen't found</B></CENTER>"; }
else { 
$inputpass = crypt($INPUT{'pass'}, "aa");
if ($inputpass eq "$cryptpass") {
print <<"HTML"; 
<META HTTP-EQUIV="Refresh" CONTENT="0;URL=members.cgi?a=frame&user=$INPUT{'user'}&pass=$INPUT{'pass'}">
<CENTER><P><BR><P><BR><A HREF="members.cgi?a=frame&user=$INPUT{'user'}&pass=$INPUT{'pass'}"><BIG>Please Wait..</B></BIG><P><BR><P><BR></CENTER> 
HTML
 }
else { print "<CENTER><B>Sorry, The Password you entered is invalied!</B></CENTER>"; }
}
}
}

## Removing this line will violate copyright laws!!
print "<CENTER><HR width=150><SMALL>Ran with <A HREF=http://perl.d0tt.com>REMOTE 2.0</A></SMALL></CENTER>";