#!/usr/bin/perl

####################################
##                                ##
##             REMOTE             ##
##  CopyRight Byron Chilton 2000  ##
##      http://www.d0tt.com       ##
##                                ##
##     DO NOT EDIT THIS FILE      ##
##                                ##
####################################

require "config.pl";

  read(STDIN, $buffer, $ENV{'CONTENT_LENGTH'});
  if (length($buffer) < 5) {
    $buffer = $ENV{QUERY_STRING};
  }
 
  @pairs = split(/&/, $buffer);
  foreach $pair (@pairs) {
    ($name, $value) = split(/=/, $pair);

    $value =~ tr/+/ /;
    $value =~ s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/eg;
    $value =~ s/[\;\|\\ ]/ /ig;
    $INPUT{$name} = $value;
}
print "Content-type: text/html\n\n";
if ($INPUT{'user'} eq "") {
print "<CENTER><B>Username error!! Please Re-login at <A HREF=$home_page>$home_page</A></B></CENTER>";
}
elsif ($INPUT{'pass'} eq "") {
print "<CENTER><B>Password error!! Please Re-login at <A HREF=$home_page>$home_page</A></B></CENTER>";
}
else {
open (FILE, "$data_path/$INPUT{'user'}.mem");
flock (FILE, 2);
$name = <FILE>;
chop ($name);
$cryptpass = <FILE>;
chop ($cryptpass);
$mail = <FILE>;
chop ($mail);
$url = <FILE>;
chop ($url);
$site_title = <FILE>;
chop ($site_title);
flock (FILE, 8);
close(FILE);

if ($name eq "") { print "<CENTER><B>Username error!! Please Re-login at <A HREF=$home_page>$home_page</A></B></CENTER>"; }
else { 
$inputpass = crypt($INPUT{'pass'}, "aa");
if ($inputpass eq "$cryptpass") { &start }
else { print "<CENTER><B><B>Password error!! Please Re-login at <A HREF=$home_page>$home_page</A></B></CENTER>"; }
}
}

sub start {
if ($INPUT{'a'} eq "nav") { &nav_frame }
elsif ($INPUT{'a'} eq "main") { &main_frame }
elsif ($INPUT{'a'} eq "frame") { &frame_set }
elsif ($INPUT{'a'} eq "editinfo") { &edit_form }
elsif ($INPUT{'a'} eq "update_info") { &update_info }
elsif ($INPUT{'a'} eq "changepass") { &change_pass }
elsif ($INPUT{'a'} eq "update_pass") { &update_pass }
elsif ($INPUT{'a'} eq "cont_code") { &cont_code_form }
elsif ($INPUT{'a'} eq "cont_code_show") { &cont_code_show }
elsif ($INPUT{'a'} eq "clock_code") { &clock_code_form }
elsif ($INPUT{'a'} eq "clock_code_show") { &clock_code_show }
elsif ($INPUT{'a'} eq "edit_cont") { &edit_cont }
elsif ($INPUT{'a'} eq "update_cont") { &update_cont }
elsif ($INPUT{'a'} eq "edit_book") { &edit_book }
elsif ($INPUT{'a'} eq "update_book") { &update_book }
elsif ($INPUT{'a'} eq "book_code") { &book_code }
elsif ($INPUT{'a'} eq "edit_gb_entry") { &edit_gb_entry }
elsif ($INPUT{'a'} eq "edit_gb_com") { &edit_gb_com }
elsif ($INPUT{'a'} eq "edit_ffal") { &edit_ffal }
elsif ($INPUT{'a'} eq "update_ffal") { &update_ffal }
elsif ($INPUT{'a'} eq "ffal_code") { &ffal_code }
elsif ($INPUT{'a'} eq "edit_ffal_entry") { &edit_ffal_entry }
elsif ($INPUT{'a'} eq "edit_ffal_com") { &edit_ffal_com }
elsif ($INPUT{'a'} eq "edit_mail") { &edit_mail }
elsif ($INPUT{'a'} eq "edit_mail_com") { &edit_mail_com }
elsif ($INPUT{'a'} eq "edit_mail_thank") { &edit_mail_thank }
elsif ($INPUT{'a'} eq "edit_mail_thank_com") { &edit_mail_thank_com }
elsif ($INPUT{'a'} eq "send_email") { &send_email }
elsif ($INPUT{'a'} eq "send_email_com") { &send_email_com }
elsif ($INPUT{'a'} eq "mail_code") { &mail_code }
elsif ($INPUT{'a'} eq "poll_code") { &poll_code }
elsif ($INPUT{'a'} eq "poll_code_com") { &poll_code_com }
elsif ($INPUT{'a'} eq "poll_edit") { &poll_edit }
elsif ($INPUT{'a'} eq "del_poll") { &del_poll }
elsif ($INPUT{'a'} eq "del_poll_com") { &del_poll_com }
elsif ($INPUT{'a'} eq "add_post_img") { &add_post_img }
elsif ($INPUT{'a'} eq "add_post_img_com") { &add_post_img_com }
elsif ($INPUT{'a'} eq "del_post_img") { &del_post_img }
elsif ($INPUT{'a'} eq "del_post_img_com") { &del_post_img_com }
elsif ($INPUT{'a'} eq "post_code") { &post_code }
elsif ($INPUT{'a'} eq "edit_post") { &edit_post }
elsif ($INPUT{'a'} eq "edit_post_com") { &edit_post_com }
elsif ($INPUT{'a'} eq "email_form_code") { &email_form_code }
elsif ($INPUT{'a'} eq "add_rand_img") { &add_rand_img }
elsif ($INPUT{'a'} eq "add_rand_img_com") { &add_rand_img_com }
elsif ($INPUT{'a'} eq "del_rand_img") { &del_rand_img }
elsif ($INPUT{'a'} eq "del_rand_img_com") { &del_rand_img_com }
elsif ($INPUT{'a'} eq "rand_code") { &rand_code }

else {
print <<"HTML";
<CENTER><B>There has been an error</B><BR>
Please informe the webmaster of the error and what you might have done to cause it!
<CENTER>
HTML
}
}

sub frame_set {
print <<"HTML";
<FRAMESET ROWS="14%,86%">
<FRAME SRC="members.cgi?a=nav&user=$INPUT{'user'}&pass=$INPUT{'pass'}" SCROLLING="No" NORESIZE>
<FRAME SRC="members.cgi?a=main&user=$INPUT{'user'}&pass=$INPUT{'pass'}" NAME="main">
</FRAMESET>
HTML
}

sub edit_form {
&member_header;
print <<"HTML";
<FORM ACTION="members.cgi" METHOD="POST">
<CENTER><TABLE BORDER CELLPADDING="2" ALIGN="Center">
<TR><TD COLSPAN=2><P ALIGN=Center>
<BIG>Change Member Data</BIG></TD>
</TR><TR><TD>E-Mail:</TD><TD>
<INPUT TYPE="text" NAME="mail" VALUE="$mail"></TD>
</TR><TR><TD>Site URL:</TD><TD>
<INPUT TYPE="text" NAME="url" VALUE="$url"></TD>
</TR><TR><TD>Site Title:</TD><TD>
<INPUT TYPE="text" NAME="site_title" VALUE="$site_title"></TD>
</TR><TR>
<TD COLSPAN=2><P ALIGN=Center>
<INPUT TYPE="hidden" NAME="user" VALUE="$name">
<INPUT TYPE="hidden" NAME="pass" VALUE="$INPUT{'pass'}">
<INPUT TYPE="hidden" NAME="a" VALUE="update_info">
<INPUT TYPE=submit VALUE="Update"></TD>
</TR></TABLE></CENTER></FORM>
HTML
}

sub update_info {
open(cnt, ">$data_path/$INPUT{'user'}.mem");
print cnt "$INPUT{'user'}\n";
print cnt "$cryptpass\n";
print cnt "$INPUT{'mail'}\n";
print cnt "$INPUT{'url'}\n";
print cnt "$INPUT{'site_title'}\n";
close(cnt);
&member_header;
print <<"HTML";
<CENTER><B>Your member data has been updated!</B></CENTER>
HTML
}

sub change_pass {
&member_header;
print <<"HTML";
<FORM ACTION="members.cgi" METHOD="POST">
<CENTER><TABLE BORDER CELLPADDING="2" ALIGN="Center">
<TR><TD COLSPAN=2><P ALIGN=Center>
<BIG>Change Password</BIG></TD>
</TR><TR><TD>New Password:</TD><TD>
<INPUT TYPE="text" NAME="newpass"></TD>
</TR><TR><TD COLSPAN=2><P ALIGN=Center>
<INPUT TYPE="hidden" NAME="user" VALUE="$name">
<INPUT TYPE="hidden" NAME="pass" VALUE="$INPUT{'pass'}">
<INPUT TYPE="hidden" NAME="a" VALUE="update_pass">
<INPUT TYPE=submit VALUE="Update"></TD></TR>
</TABLE></CENTER></FORM>
HTML
}

sub update_pass {
$cryptpass = crypt($INPUT{'newpass'}, "aa");

open(cnt, ">$data_path/$INPUT{'user'}.mem");
print cnt "$INPUT{'user'}\n";
print cnt "$cryptpass\n";
print cnt "$INPUT{'mail'}\n";
print cnt "$INPUT{'url'}\n";
print cnt "$INPUT{'site_title'}\n";
close(cnt);
&member_header;
print <<"HTML";
<CENTER>You Must ReLogin to complet the password update!<BR>
<A HREF=members.cgi?a=frame&user=$INPUT{'user'}&pass=$INPUT{'newpass'} target=_top>Click Here To ReLogin</A></CENTER>
HTML
}

sub cont_code_form {
&member_header;
print <<"HTML";
<FORM ACTION="members.cgi" METHOD="POST">
<CENTER><TABLE BORDER CELLPADDING="2" ALIGN="Center">
<TR><TD COLSPAN=2><P ALIGN=Center>
<BIG>Counter Code</BIG></TD></TR><TR>
<TD COLSPAN=2><P ALIGN=Center>Digit Style:</TD></TR><TR><TD COLSPAN=2><CENTER>
<TABLE BORDER CELLPADDING="2" ALIGN="Center">
HTML
open (DATA, "cont.txt");
@data = <DATA>;
close DATA;
foreach $line (@data) {
chomp ($line);
($digit, $width, $height) = split(/::/, $line);
print "<TR><TD><INPUT TYPE=\"radio\" NAME=\"digit\" VALUE=\"$digit\"></TD>\n";
print "<TD><IMG SRC=\"$html_image_directory/$digit/1.gif\"><IMG SRC=\"$html_image_directory/$digit/2.gif\">";
print "<IMG SRC=\"$html_image_directory/$digit/3.gif\"><IMG SRC=\"$html_image_directory/$digit/4.gif\">";
print "<IMG SRC=\"$html_image_directory/$digit/5.gif\"></TD></TR>\n";
}
print <<"HTML";
</TR></TABLE>
</CENTER></TD></TR><TR><TD>PageName:</TD><TD>
<INPUT TYPE="text" NAME="page" SIZE="15"></TD></TR><TR>
<TD>DigitsShown:</TD><TD>
<INPUT TYPE="text" NAME="size" SIZE="3"></TD>
</TR><TR>
<TD>Disabel Re-load:</TD><TD>
<INPUT TYPE="radio" NAME="re" VALUE="1" CHECKED>yes &nbsp; &nbsp;
<INPUT TYPE="radio" NAME="re" VALUE="0">no</TD>
</TR><TR><TD COLSPAN=2><P ALIGN=Center>
<INPUT TYPE="hidden" NAME="user" VALUE="$INPUT{'user'}">
<INPUT TYPE="hidden" NAME="pass" VALUE="$INPUT{'pass'}">
<INPUT TYPE="hidden" NAME="a" VALUE="cont_code_show">
<INPUT TYPE=submit VALUE="Show Code"></TD>
</TR></TABLE></CENTER></FORM>
HTML
}

sub cont_code_show {
open (DATA, "cont.txt");
@data = <DATA>;
close DATA;
foreach $line (@data) {
chomp ($line);
($digit, $width, $height) = split(/::/, $line);
if ($INPUT{'digit'} eq "$digit") {
$Adigit = "$digit";
$Awidth = "$width";
$Aheight = "$height";
}
}
print <<"HTML";
<CENTER><TABLE BORDER CELLPADDING="2">
<TR><TD><P ALIGN=Center>
<BIG>Counter Code:</BIG></TD>
</TR><TR><TD><P ALIGN=Center>
Copy and paste this code into your pages html
<P ALIGN=Center>
<FONT COLOR="#ff0000"><SMALL>&lt;Center&gt;&lt;A HREF="$home_page"&gt;&lt;IMG
SRC="$html_cgi_path/counter.cgi?u=$INPUT{'user'}&p=$INPUT{'page'}&z=$INPUT{'size'}&h=$Aheight&w=$Awidth&s=$Adigit&r=$INPUT{'re'}" 
BORDER="0"&gt;&lt;/A&gt;&lt;/CENTER&gt;</SMALL></FONT></TD>
</TR></TABLE></CENTER>
HTML
}

sub clock_code_form {
&member_header;
print <<"HTML";
<FORM ACTION="members.cgi" METHOD="POST">
<CENTER><TABLE BORDER CELLPADDING="2" ALIGN="Center">
<TR><TD COLSPAN=2><P ALIGN=Center>
<BIG>Clock Code</BIG></TD></TR><TR>
<TD COLSPAN=2><P ALIGN=Center>Digit Style:</TD></TR><TR><TD COLSPAN=2><CENTER>
<TABLE BORDER CELLPADDING="2" ALIGN="Center">
HTML
open (DATA, "clock.txt");
@data = <DATA>;
close DATA;
foreach $line (@data) {
chomp ($line);
($digit, $width, $height) = split(/::/, $line);
print "<TR><TD><INPUT TYPE=\"radio\" NAME=\"digit\" VALUE=\"$digit\"></TD>\n";
print "<TD><IMG SRC=\"$html_image_directory/$digit/1.gif\"><IMG SRC=\"$html_image_directory/$digit/2.gif\">";
print "<IMG SRC=\"$html_image_directory/$digit/3.gif\">";
print "<IMG SRC=\"$html_image_directory/$digit/4.gif\"><IMG SRC=\"$html_image_directory/$digit/5.gif\"></TD></TR>\n";
}
print <<"HTML";
</TR></TABLE>
</CENTER></TD></TR><TR><TD COLSPAN=2><P ALIGN=Center>
<INPUT TYPE="hidden" NAME="user" VALUE="$INPUT{'user'}">
<INPUT TYPE="hidden" NAME="pass" VALUE="$INPUT{'pass'}">
<INPUT TYPE="hidden" NAME="a" VALUE="clock_code_show">
<INPUT TYPE=submit VALUE="Show Code"></TD>
</TR></TABLE></CENTER></FORM>
HTML
}

sub clock_code_show {
open (DATA, "clock.txt");
@data = <DATA>;
close DATA;
foreach $line (@data) {
chomp ($line);
($digit, $width, $height) = split(/::/, $line);
if ($INPUT{'digit'} eq "$digit") {
$Adigit = "$digit";
$Awidth = "$width";
$Aheight = "$height";
}
}
print <<"HTML";
<CENTER><TABLE BORDER CELLPADDING="2">
<TR><TD><P ALIGN=Center>
<BIG>Clock Code:</BIG></TD>
</TR><TR><TD><P ALIGN=Center>
Copy and paste this code into your pages html
<P ALIGN=Center>
<FONT COLOR="#ff0000"><SMALL>&lt;Center&gt;&lt;A HREF="$home_page"&gt;&lt;IMG
SRC="$html_cgi_path/clock.cgi?h=$Aheight&w=$Awidth&s=$Adigit&u=$INPUT{'user'}" BORDER="0"&gt;&lt;/A&gt;&lt;/CENTER&gt;</SMALL></FONT></TD>
</TR></TABLE></CENTER>
HTML
}

sub edit_cont {
&member_header;
print <<"HTML";
<FORM ACTION="members.cgi" METHOD="POST">
<CENTER><TABLE BORDER CELLPADDING="2" ALIGN="Center">
<TR><TD COLSPAN=2><P ALIGN=Center>
<BIG>Edit Counter</BIG></TD></TR><TR>
<TD COLSPAN=2><P ALIGN=Center>Counters:</TD></TR><TR><TD COLSPAN=2><CENTER>
<TABLE BORDER CELLPADDING="2" ALIGN="Center">
<TR><TD></TD>
<TD>Name</TD><TD>Hits</TD></TR>
HTML
open (DATA, "$data_path/$INPUT{'user'}.cnt");
@data = <DATA>;
close DATA;
foreach $line (@data) {
chomp ($line);
($name, $hit, $ip) = split(/::/, $line);
print "<TR><TD><INPUT TYPE=\"radio\" NAME=\"name\" VALUE=\"$name\"></TD>\n";
print "<TD>$name</TD><TD>$hit</TD></TR>\n";
}
print <<"HTML";
</TR></TABLE>
</CENTER></TD></TR>
<TR><TD>Change Hits to:</TD><TD>
<INPUT TYPE="text" NAME="count"></TD></TR>

<TR><TD COLSPAN=2><P ALIGN=Center>
<INPUT TYPE="hidden" NAME="user" VALUE="$INPUT{'user'}">
<INPUT TYPE="hidden" NAME="pass" VALUE="$INPUT{'pass'}">
<INPUT TYPE="hidden" NAME="a" VALUE="update_cont">
<INPUT TYPE=submit NAME="submit" VALUE="Update">
<INPUT TYPE=submit NAME="submit" VALUE="Delete">
</TD>
</TR></TABLE></CENTER></FORM>
HTML
}

sub update_cont {
if ($INPUT{'submit'} eq "Update") {
open (DATA, "$data_path/$INPUT{'user'}.cnt");
@data = <DATA>;
close DATA;
open(cnt, ">$data_path/$INPUT{'user'}.cnt");
foreach $line (@data) {
chomp ($line);
($name, $hit, $ip) = split(/::/, $line);
if ($name eq "$INPUT{'name'}") {
print cnt "$INPUT{'name'}::$INPUT{'count'}::123::\n";
}
else {
print cnt "$line\n";
}
}
close cnt;
print "<CENTER><B>Counter Updated</B></CENTER>";
}
if ($INPUT{'submit'} eq "Delete") {
open (DATA, "$data_path/$INPUT{'user'}.cnt");
@data = <DATA>;
close DATA;
open(cnt, ">$data_path/$INPUT{'user'}.cnt");
foreach $line (@data) {
chomp ($line);
($name, $hit, $ip) = split(/::/, $line);
if ($name eq "$INPUT{'name'}") {
print cnt "";
}
else {
print cnt "$line\n";
}
}
close cnt;
print "<CENTER><B>Counter Deleted</B></CENTER>";
}
}

sub edit_book {
open (FILE, "$data_path/$INPUT{'user'}.gbc");
flock (FILE, 2);
$text = <FILE>;
chop ($text);
$link = <FILE>;
chop ($link);
$vlink = <FILE>;
chop ($vlink);
$bg = <FILE>;
chop ($bg);
$image = <FILE>;
chop ($image);
$return = <FILE>;
chop ($return);
$heading = <FILE>;
chop ($heading);
flock (FILE, 8);
close(FILE);
if ($text eq "") { $text = "#000000"; }
if ($link eq "") { $link = "#0000ff"; }
if ($vlink eq "") { $vlink = "#ff8080"; }
if ($bg eq "") { $bg = "#ffffff"; }
if ($return eq "") { $return = "$url"; }
if ($heading eq "") { $heading = "$name GuestBook"; }

print <<"HTML";
<FORM ACTION="members.cgi" METHOD="POST">
<CENTER><TABLE BORDER CELLPADDING="2" ALIGN="Center">
<TR><TD COLSPAN=2><P ALIGN=Center>
<BIG>Edit GuestBook:</BIG></TD>
</TR><TR><TD>Text Color:</TD><TD>
<INPUT TYPE="text" NAME="text" VALUE="$text"></TD>
</TR><TR><TD>Link Color:</TD><TD>
<INPUT TYPE="text" NAME="link" VALUE="$link"></TD>
</TR><TR><TD>Visited Link Color:</TD><TD>
<INPUT TYPE="text" NAME="vlink" VALUE="$vlink"></TD>
</TR><TR><TD>BackGround Color:</TD><TD>
<INPUT TYPE="text" NAME="bg" VALUE="$bg"></TD>
</TR><TR><TD>BackGround Image:</TD><TD>
<INPUT TYPE="text" NAME="image" VALUE="$image"></TD>
</TR><TR><TD>Return Link:</TD><TD>
<INPUT TYPE="text" NAME="return" VALUE="$return"></TD>
</TR><TR><TD>Heading:</TD><TD>
<INPUT TYPE="text" NAME="heading" VALUE="$heading"></TD>
</TR><TR><TD COLSPAN=2><P ALIGN=Center>
<INPUT TYPE="hidden" NAME="user" VALUE="$INPUT{'user'}">
<INPUT TYPE="hidden" NAME="pass" VALUE="$INPUT{'pass'}">
<INPUT TYPE="hidden" NAME="a" VALUE="update_book">
<INPUT TYPE=submit VALUE="Update"></TD>
</TR></TABLE></CENTER></FORM>
HTML
}

sub update_book {
open(cnt, ">$data_path/$INPUT{'user'}.gbc");
print cnt "$INPUT{'text'}\n";
print cnt "$INPUT{'link'}\n";
print cnt "$INPUT{'vlink'}\n";
print cnt "$INPUT{'bg'}\n";
print cnt "$INPUT{'image'}\n";
print cnt "$INPUT{'return'}\n";
print cnt "$INPUT{'heading'}\n";
close(cnt);
&member_header;
print <<"HTML";
<CENTER><B>GuestBook Updated</B></CENTER>
HTML
}

sub book_code {
print <<"HTML";
<CENTER><TABLE BORDER CELLPADDING="2">
<TR><TD><P ALIGN=Center>
<BIG>GuestBook Code:</BIG></TD>
</TR><TR><TD><P ALIGN=Center>
Copy and paste this code into your pages html
<P ALIGN=Center>
<FONT COLOR="#ff0000"><SMALL>
&lt;CENTER&gt;&lt;A
HREF="$html_cgi_path/guestbook.cgi?a=sign&amp;user=$INPUT{'user'}"&gt;Sign
GuestBook&lt;/A&gt;&lt;BR&gt;<BR>
&lt;A
HREF="$html_cgi_path/guestbook.cgi?a=view&amp;user=$INPUT{'user'}"&gt;View
GuestBook&lt;/A&gt;&lt;/CENTER&gt;
</SMALL></FONT></TD>
</TR></TABLE></CENTER>
HTML
}

sub edit_gb_entry {
&member_header;
print <<"HTML";
<FORM ACTION="members.cgi" METHOD="POST">
<CENTER><TABLE BORDER CELLPADDING="2" ALIGN="Center">
<TR><TD COLSPAN=2><P ALIGN=Center>
<BIG>Edit GuestBook Entrys</BIG></TD></TR><TR>
<TD COLSPAN=2><P ALIGN=Center>Entryes:</TD></TR><TR><TD COLSPAN=2><CENTER>
<CENTER><TABLE BORDER CELLPADDING="2" ALIGN="Center"><TR>
<TD></TD><TD>Name</TD><TD>E-Mail</TD><TD>URL</TD><TD>Title</TD><TD>Comment</TD></TR>
HTML
$nmb = "0";
open (DATA, "$data_path/$INPUT{'user'}.gbd");
@data = <DATA>;
close DATA;
foreach $line (@data) {
$nmb++;
chomp ($line);
($name, $email, $url, $title, $comment) = split(/::/, $line);
print "<TR><TD><INPUT TYPE=\"radio\" NAME=\"nmb\" VALUE=\"$nmb\"></TD>\n";
print "<TD>$name</TD><TD><A HREF=\"mailto:$email\">$email</A></TD>\n";
print "<TD><A HREF=\"$url\">$url</A></TD><TD>$title</TD><TD>$comment</TD></TR>\n";
}
print <<"HTML";
</TABLE></CENTER>
</CENTER></TD></TR><TR><TD COLSPAN=2><P ALIGN=Center>
<INPUT TYPE="hidden" NAME="user" VALUE="$INPUT{'user'}">
<INPUT TYPE="hidden" NAME="pass" VALUE="$INPUT{'pass'}">
<INPUT TYPE="hidden" NAME="a" VALUE="edit_gb_com">
<INPUT TYPE=submit VALUE="Delete Entry"></TD>
</TR></TABLE></CENTER></FORM>
HTML
}

sub edit_gb_com {
$nmb = "0";
open (DATA, "$data_path/$INPUT{'user'}.gbd");
@data = <DATA>;
close DATA;
open(DATA, ">$data_path/$INPUT{'user'}.gbd");
foreach $line (@data) {
$nmb++;
chomp ($line);
($name, $email, $url, $title, $comment) = split(/::/, $line);
if ($nmb eq "$INPUT{'nmb'}") {
print DATA "";
}
else {
print DATA "$line\n";
}
}
close DATA;
&member_header;
print <<"HTML";
<CENTER><B>GuestBook Entry Deleted</B></CENTER>
HTML
}

sub edit_ffal {
open (FILE, "$data_path/$INPUT{'user'}.ffc");
flock (FILE, 2);
$text = <FILE>;
chop ($text);
$link = <FILE>;
chop ($link);
$vlink = <FILE>;
chop ($vlink);
$bg = <FILE>;
chop ($bg);
$image = <FILE>;
chop ($image);
$return = <FILE>;
chop ($return);
$heading = <FILE>;
chop ($heading);
flock (FILE, 8);
close(FILE);
if ($text eq "") { $text = "#000000"; }
if ($link eq "") { $link = "#0000ff"; }
if ($vlink eq "") { $vlink = "#ff8080"; }
if ($bg eq "") { $bg = "#ffffff"; }
if ($return eq "") { $return = "$url"; }
if ($heading eq "") { $heading = "$name Free for all links"; }

print <<"HTML";
<FORM ACTION="members.cgi" METHOD="POST">
<CENTER><TABLE BORDER CELLPADDING="2" ALIGN="Center">
<TR><TD COLSPAN=2><P ALIGN=Center>
<BIG>Edit GuestBook:</BIG></TD>
</TR><TR><TD>Text Color:</TD><TD>
<INPUT TYPE="text" NAME="text" VALUE="$text"></TD>
</TR><TR><TD>Link Color:</TD><TD>
<INPUT TYPE="text" NAME="link" VALUE="$link"></TD>
</TR><TR><TD>Visited Link Color:</TD><TD>
<INPUT TYPE="text" NAME="vlink" VALUE="$vlink"></TD>
</TR><TR><TD>BackGround Color:</TD><TD>
<INPUT TYPE="text" NAME="bg" VALUE="$bg"></TD>
</TR><TR><TD>BackGround Image:</TD><TD>
<INPUT TYPE="text" NAME="image" VALUE="$image"></TD>
</TR><TR><TD>Return Link:</TD><TD>
<INPUT TYPE="text" NAME="return" VALUE="$return"></TD>
</TR><TR><TD>Heading:</TD><TD>
<INPUT TYPE="text" NAME="heading" VALUE="$heading"></TD>
</TR><TR><TD COLSPAN=2><P ALIGN=Center>
<INPUT TYPE="hidden" NAME="user" VALUE="$INPUT{'user'}">
<INPUT TYPE="hidden" NAME="pass" VALUE="$INPUT{'pass'}">
<INPUT TYPE="hidden" NAME="a" VALUE="update_ffal">
<INPUT TYPE=submit VALUE="Update"></TD>
</TR></TABLE></CENTER></FORM>
HTML
}

sub update_ffal {
open(cnt, ">$data_path/$INPUT{'user'}.ffc");
print cnt "$INPUT{'text'}\n";
print cnt "$INPUT{'link'}\n";
print cnt "$INPUT{'vlink'}\n";
print cnt "$INPUT{'bg'}\n";
print cnt "$INPUT{'image'}\n";
print cnt "$INPUT{'return'}\n";
print cnt "$INPUT{'heading'}\n";
close(cnt);
&member_header;
print <<"HTML";
<CENTER><B>Free for all links Updated</B></CENTER>
HTML
}

sub ffal_code {
print <<"HTML";
<CENTER><TABLE BORDER CELLPADDING="2">
<TR><TD><P ALIGN=Center>
<BIG>Free for all links Code:</BIG></TD>
</TR><TR><TD><P ALIGN=Center>
Copy and paste this code into your pages html
<P ALIGN=Center>
<FONT COLOR="#ff0000"><SMALL>
&lt;CENTER&gt;&lt;A
HREF="$html_cgi_path/ffal.cgi?a=sign&user=$INPUT{'user'}"&gt;Add Link&lt;/A&gt;&lt;BR&gt;<BR>
&lt;A
HREF="$html_cgi_path/ffal.cgi?a=view&amp;user=$INPUT{'user'}"&gt;View
Links&lt;/A&gt;&lt;/CENTER&gt;
</SMALL></FONT></TD>
</TR></TABLE></CENTER>
HTML
}

sub edit_ffal_entry {
&member_header;
print <<"HTML";
<FORM ACTION="members.cgi" METHOD="POST">
<CENTER><TABLE BORDER CELLPADDING="2" ALIGN="Center">
<TR><TD COLSPAN=2><P ALIGN=Center>
<BIG>Edit Free for all links Entrys</BIG></TD></TR><TR>
<TD COLSPAN=2><P ALIGN=Center>Entryes:</TD></TR><TR><TD COLSPAN=2><CENTER>
<CENTER><TABLE BORDER CELLPADDING="2" ALIGN="Center"><TR>
<TD></TD><TD>Name</TD><TD>E-Mail</TD><TD>URL</TD><TD>Title</TD><TD>Comment</TD></TR>
HTML
$nmb = "0";
open (DATA, "$data_path/$INPUT{'user'}.ffd");
@data = <DATA>;
close DATA;
foreach $line (@data) {
$nmb++;
chomp ($line);
($name, $email, $url, $title, $comment) = split(/::/, $line);
print "<TR><TD><INPUT TYPE=\"radio\" NAME=\"nmb\" VALUE=\"$nmb\"></TD>\n";
print "<TD>$name</TD><TD><A HREF=\"mailto:$email\">$email</A></TD>\n";
print "<TD><A HREF=\"$url\">$url</A></TD><TD>$title</TD><TD>$comment</TD></TR>\n";
}
print <<"HTML";
</TABLE></CENTER>
</CENTER></TD></TR><TR><TD COLSPAN=2><P ALIGN=Center>
<INPUT TYPE="hidden" NAME="user" VALUE="$INPUT{'user'}">
<INPUT TYPE="hidden" NAME="pass" VALUE="$INPUT{'pass'}">
<INPUT TYPE="hidden" NAME="a" VALUE="edit_ffal_com">
<INPUT TYPE=submit VALUE="Delete Entry"></TD>
</TR></TABLE></CENTER></FORM>
HTML
}

sub edit_ffal_com {
$nmb = "0";
open (DATA, "$data_path/$INPUT{'user'}.ffd");
@data = <DATA>;
close DATA;
open(DATA, ">$data_path/$INPUT{'user'}.ffd");
foreach $line (@data) {
$nmb++;
chomp ($line);
($name, $email, $url, $title, $comment) = split(/::/, $line);
if ($nmb eq "$INPUT{'nmb'}") {
print DATA "";
}
else {
print DATA "$line\n";
}
}
close DATA;
&member_header;
print <<"HTML";
<CENTER><B>Free for all link Entry Deleted</B></CENTER>
HTML
}

sub edit_mail {
&member_header;
print <<"HTML";
<FORM ACTION="members.cgi" METHOD="POST">
<CENTER><TABLE BORDER CELLPADDING="2" ALIGN="Center">
<TR><TD COLSPAN=2><P ALIGN=Center>
<BIG>Mailing list Entrys</BIG></TD></TR><TR>
<TD COLSPAN=2><P ALIGN=Center>Entryes:</TD></TR><TR><TD COLSPAN=2><CENTER>
<CENTER><TABLE BORDER CELLPADDING="2" ALIGN="Center"><TR>
<TD></TD><TD>E-Mail</TD></TR>
HTML
$nmb = "0";
open (DATA, "$data_path/$INPUT{'user'}.mld");
@data = <DATA>;
close DATA;
foreach $line (@data) {
$nmb++;
chomp ($line);
print "<TR><TD><INPUT TYPE=\"radio\" NAME=\"nmb\" VALUE=\"$nmb\"></TD>\n";
print "<TD>$line</TD></TR>\n";
}
print <<"HTML";
</TABLE></CENTER>
</CENTER></TD></TR><TR><TD COLSPAN=2><P ALIGN=Center>
<INPUT TYPE="hidden" NAME="user" VALUE="$INPUT{'user'}">
<INPUT TYPE="hidden" NAME="pass" VALUE="$INPUT{'pass'}">
<INPUT TYPE="hidden" NAME="a" VALUE="edit_mail_com">
<INPUT TYPE=submit VALUE="Delete E-Mail"></TD>
</TR></TABLE></CENTER></FORM>
HTML
}

sub edit_mail_com {
$nmb = "0";
open (DATA, "$data_path/$INPUT{'user'}.mld");
@data = <DATA>;
close DATA;
open(DATA, ">$data_path/$INPUT{'user'}.mld");
foreach $line (@data) {
$nmb++;
chomp ($line);
if ($nmb eq "$INPUT{'nmb'}") {
print DATA "";
}
else {
print DATA "$line\n";
}
}
close DATA;
&member_header;
print <<"HTML";
<CENTER><B>E-Mail Deleted</B></CENTER>
HTML
}

sub mail_code {
&member_header;
print <<"HTML";
<CENTER><TABLE BORDER CELLPADDING="2">
<TR><TD><P ALIGN=Center>
<BIG>Mailing list code:</BIG></TD>
</TR><TR><TD><P ALIGN=Center>
Copy and paste this code into your pages html
<P ALIGN=Center>
<FONT COLOR="#ff0000"><SMALL>
&lt;FORM ACTION="$html_cgi_path/mail.cgi" METHOD="POST"&gt;<BR>
&lt;CENTER&gt;&lt;TABLE BORDER CELLPADDING="2" ALIGN="Center"&gt;<BR>
&lt;TR&gt;&lt;TD COLSPAN=2&gt;&lt;BIG&gt;Join Our Mailing
list&lt;/BIG&gt;&lt;/TD&gt;<BR>
&lt;/TR&gt;&lt;TR&gt;&lt;TD&gt;E-Mail:&lt;/TD&gt;&lt;TD&gt;<BR>
&lt;INPUT TYPE="text" NAME="email"&gt;&lt;/TD&gt;<BR>
&lt;/TR&gt;&lt;TR&gt;&lt;TD COLSPAN=2&gt;&lt;P ALIGN=Center&gt;<BR>
&lt;INPUT TYPE="radio" NAME="a" VALUE="sub" CHECKED&gt;Subscribe &amp;nbsp;<BR>
&lt;INPUT TYPE="radio" NAME="a"
VALUE="rev"&gt;Remove&lt;/TD&gt;&lt;/TR&gt;<BR>
&lt;TR&gt;&lt;TD COLSPAN=2&gt;&lt;P ALIGN=Center&gt;<BR>
&lt;INPUT TYPE="hidden" NAME="user" VALUE="$INPUT{'user'}"&gt;<BR>
&lt;INPUT TYPE=submit VALUE="Join"&gt;&lt;/TD&gt;<BR>
&lt;/TR&gt;&lt;/TABLE&gt;&lt;/CENTER&gt;&lt;/FORM&gt;
</SMALL></FONT></TD>
</TR></TABLE></CENTER>
HTML
}

sub edit_mail_thank {
open (DATA, "$data_path/$INPUT{'user'}.mlt");
$data = <DATA>;
close DATA;
&member_header;
print <<"HTML";
<FORM ACTION="members.cgi" METHOD="POST">
<CENTER><TABLE BORDER CELLPADDING="2" ALIGN="Center">
<TR><TD><P ALIGN=Center>
<BIG>Edit Mailing List thank you message</BIG></TD></TR>
<TR><TD><P ALIGN=Center>
<TEXTAREA NAME="mess" ROWS="5" COLS="18">$data</TEXTAREA></TD>
</TR><TR><TD><P ALIGN=Center>
<INPUT TYPE="hidden" NAME="user" VALUE="$INPUT{'user'}">
<INPUT TYPE="hidden" NAME="pass" VALUE="$INPUT{'pass'}">
<INPUT TYPE="hidden" NAME="a" VALUE="edit_mail_thank_com">
<INPUT TYPE=submit VALUE="Update"></TD>
</TR></TABLE></CENTER></FORM>
HTML
}

sub edit_mail_thank_com {
open (DATA, "$data_path/$INPUT{'user'}.mlt");
@data = <DATA>;
close DATA;
open(DATA, ">$data_path/$INPUT{'user'}.mlt");
print DATA "$INPUT{'mess'}";
close DATA;
&member_header;
print <<"HTML";
<CENTER><B>Thank you message updated</B></CENTER>
HTML
}

sub send_email {
&member_header;
print <<"HTML";
<FORM ACTION="members.cgi" METHOD="POST">
<CENTER><TABLE BORDER CELLPADDING="2" ALIGN="Center">
<TR><TD COLSPAN=2><P ALIGN=Center>
<BIG>Edit Mailing List thank you message</BIG></TD>
</TR><TR><TD>Subject:</TD><TD>
<INPUT TYPE="text" NAME="subject"></TD>
</TR><TR><TD>Message:</TD>
<TD><TEXTAREA NAME="message" ROWS="5" COLS="18"></TEXTAREA></TD>
</TR><TR><TD COLSPAN=2><P ALIGN=Center>
<INPUT TYPE="hidden" NAME="user" VALUE="$INPUT{'user'}">
<INPUT TYPE="hidden" NAME="pass" VALUE="$INPUT{'pass'}">
<INPUT TYPE="hidden" NAME="a" VALUE="send_email_com">
<INPUT TYPE=submit VALUE="Send Mails"></TD>
</TR></TABLE></CENTER></FORM>
HTML
}

sub send_email_com {
open (DATA, "$data_path/$INPUT{'user'}.mld");
@data = <DATA>;
close DATA;
foreach $line (@data) {
chomp ($line);
open (MAIL, "| $mailprog -t -oi") || die "Can't open $mailprog";
print MAIL "To: $line\n";
print MAIL "Reply-to: $mail\n";
print MAIL "From: $mail\n";
print MAIL "Subject: $INPUT{'subject'}\n";
print MAIL "$INPUT{'message'}\n";
}
&member_header;
print <<"HTML";
<CENTER><B>Emails sent</B></CENTER>
HTML
}

sub poll_code {
open (FILE, "$data_path/$INPUT{'user'}.wpd");
flock (FILE, 2);
$title = <FILE>;
chop ($title);
$qust = <FILE>;
chop ($qust);
$idem1 = <FILE>;
chop ($idem1);
$idem2 = <FILE>;
chop ($idem2);
$idem3 = <FILE>;
chop ($idem3);
$idem4 = <FILE>;
chop ($idem4);
$value1 = <FILE>;
chop ($value1);
$value2 = <FILE>;
chop ($value2);
$value3 = <FILE>;
chop ($value3);
$value4 = <FILE>;
chop ($value4);
flock (FILE, 8);
close(FILE);
if ($title eq "") { 
&member_header;
print <<"HTML";
<FORM ACTION="members.cgi" METHOD="POST">
<CENTER><TABLE BORDER CELLPADDING="2" ALIGN="Center">
<TR><TD COLSPAN=2><P ALIGN=Center>
<BIG>WebPoll Code</BIG></TD>
</TR><TR><TD>Qusten:</TD><TD>
<INPUT TYPE="text" NAME="qus"></TD>
</TR><TR><TD>Title:</TD><TD>
<INPUT TYPE="text" NAME="title"></TD>
</TR><TR><TD>Answer 1:</TD><TD>
<INPUT TYPE="text" NAME="ans1"></TD>
</TR><TR><TD>Answer 2:</TD><TD>
<INPUT TYPE="text" NAME="ans2"></TD>
</TR><TR><TD>Answer 3:</TD><TD>
<INPUT TYPE="text" NAME="ans3"></TD>
</TR><TR><TD>Answer 4:</TD><TD>
<INPUT TYPE="text" NAME="ans4"></TD>
</TR><TR><TD COLSPAN=2><P ALIGN=Center>
<INPUT TYPE="hidden" NAME="user" VALUE="$INPUT{'user'}">
<INPUT TYPE="hidden" NAME="pass" VALUE="$INPUT{'pass'}">
<INPUT TYPE="hidden" NAME="value1" VALUE="0">
<INPUT TYPE="hidden" NAME="value2" VALUE="0">
<INPUT TYPE="hidden" NAME="value3" VALUE="0">
<INPUT TYPE="hidden" NAME="value4" VALUE="0">
<INPUT TYPE="hidden" NAME="a" VALUE="poll_code_com">
<INPUT TYPE=submit VALUE="Show code"></TD>
</TR></TABLE></CENTER></FORM>
HTML
}
else {
print "<CENTER><B>You already have a webpoll!!</B><BR>Please delete the old one to make a new one</CENTER>";
}
}

sub poll_code_com {
open(cnt, ">$data_path/$INPUT{'user'}.wpd");
print cnt "$INPUT{'title'}\n";
print cnt "$INPUT{'qus'}\n";
print cnt "$INPUT{'ans1'}\n";
print cnt "$INPUT{'ans2'}\n";
print cnt "$INPUT{'ans3'}\n";
print cnt "$INPUT{'ans4'}\n";
print cnt "$INPUT{'value1'}\n";
print cnt "$INPUT{'value2'}\n";
print cnt "$INPUT{'value3'}\n";
print cnt "$INPUT{'value4'}\n";
close(cnt);

&member_header;
print <<"HTML";
<CENTER><TABLE BORDER CELLPADDING="2">
<TR><TD><P ALIGN=Center>
<BIG>WebPoll code:</BIG></TD>
</TR><TR><TD><P ALIGN=Center>
Copy and paste this code into your pages html
<P ALIGN=Center>
<FONT COLOR="#ff0000"><SMALL>
&lt;FORM ACTION="$html_cgi_path/poll.cgi" METHOD="POST"&gt;<BR>
&lt;CENTER&gt;&lt;TABLE BORDER CELLPADDING="2" ALIGN="Center"&gt;<BR>
&lt;TR&gt;&lt;TD COLSPAN=2&gt;&lt;P ALIGN=Center&gt;<BR>
&lt;BIG&gt;$INPUT{'title'}&lt;/BIG&gt;&lt;/TD&gt;&lt;/TR&gt;&lt;TR&gt;<BR>
&lt;TD COLSPAN=2&gt;&lt;P
ALIGN=Center&gt;$INPUT{'qus'}&lt;/TD&gt;&lt;/TR&gt;&lt;TR&gt;&lt;TD&gt;<BR>
&lt;INPUT TYPE="radio" NAME="idem" VALUE="1"&gt;&lt;/TD&gt;<BR>
&lt;TD&gt;$INPUT{'ans1'}&lt;/TD&gt;&lt;/TR&gt;&lt;TR&gt;&lt;TD&gt;<BR>
&lt;INPUT TYPE="radio" NAME="idem" VALUE="2"&gt;&lt;/TD&gt;<BR>
&lt;TD&gt;$INPUT{'ans2'}&lt;/TD&gt;&lt;/TR&gt;&lt;TR&gt;&lt;TD&gt;<BR>
&lt;INPUT TYPE="radio" NAME="idem" VALUE="3"&gt;&lt;/TD&gt;<BR>
&lt;TD&gt;$INPUT{'ans3'}&lt;/TD&gt;&lt;/TR&gt;&lt;TR&gt;&lt;TD&gt;<BR>
&lt;INPUT TYPE="radio" NAME="idem" VALUE="4"&gt;&lt;/TD&gt;<BR>
&lt;TD&gt;$INPUT{'ans4'}&lt;/TD&gt;<BR>
&lt;/TR&gt;&lt;TR&gt;&lt;TD COLSPAN=2&gt;&lt;P ALIGN=Center&gt;<BR>
&lt;INPUT TYPE="hidden" NAME="u" VALUE="$INPUT{'user'}"&gt;<BR>
&lt;INPUT TYPE=submit VALUE="Vote"&gt;&lt;/TD&gt;<BR>
&lt;/TR&gt;&lt;/TABLE&gt;&lt;/CENTER&gt;&lt;/FORM&gt;
</SMALL></FONT></TD>
</TR></TABLE></CENTER>
HTML
}

sub poll_edit {
open (FILE, "$data_path/$INPUT{'user'}.wpd");
flock (FILE, 2);
$title = <FILE>;
chop ($title);
$qust = <FILE>;
chop ($qust);
$idem1 = <FILE>;
chop ($idem1);
$idem2 = <FILE>;
chop ($idem2);
$idem3 = <FILE>;
chop ($idem3);
$idem4 = <FILE>;
chop ($idem4);
$value1 = <FILE>;
chop ($value1);
$value2 = <FILE>;
chop ($value2);
$value3 = <FILE>;
chop ($value3);
$value4 = <FILE>;
chop ($value4);
flock (FILE, 8);
close(FILE);

&member_header;
print <<"HTML";
<FORM ACTION="members.cgi" METHOD="POST">
<CENTER><TABLE BORDER CELLPADDING="2" ALIGN="Center">
<TR><TD COLSPAN=2><P ALIGN=Center>
<BIG>WebPoll Code</BIG></TD>
</TR><TR><TD>Qusten:</TD><TD>
<INPUT TYPE="text" NAME="qus" VALUE="$qust"></TD>
</TR><TR><TD>Title:</TD><TD>
<INPUT TYPE="text" NAME="title" VALUE="$title"></TD>
</TR><TR><TD>Answer 1:</TD><TD>
<INPUT TYPE="text" NAME="ans1" VALUE="$idem1"></TD>
</TR><TR><TD>Answer 2:</TD><TD>
<INPUT TYPE="text" NAME="ans2" VALUE="$idem2"></TD>
</TR><TR><TD>Answer 3:</TD><TD>
<INPUT TYPE="text" NAME="ans3" VALUE="$idem3"></TD>
</TR><TR><TD>Answer 4:</TD><TD>
<INPUT TYPE="text" NAME="ans4" VALUE="$idem4"></TD>
</TR><TR><TD COLSPAN=2><P ALIGN=Center>
<INPUT TYPE="hidden" NAME="user" VALUE="$INPUT{'user'}">
<INPUT TYPE="hidden" NAME="pass" VALUE="$INPUT{'pass'}">
<INPUT TYPE="hidden" NAME="value1" VALUE="$value1">
<INPUT TYPE="hidden" NAME="value2" VALUE="$value2">
<INPUT TYPE="hidden" NAME="value3" VALUE="$value3">
<INPUT TYPE="hidden" NAME="value4" VALUE="$value4">
<INPUT TYPE="hidden" NAME="a" VALUE="poll_code_com">
<INPUT TYPE=submit VALUE="Update WebPoll"></TD>
</TR></TABLE></CENTER></FORM>
HTML
}

sub del_poll {
&member_header;
print <<"HTML";
<CENTER><B>Are you sure you want to delete your webpoll?</B><BR>
Data from webpolls cant not be recoverd!<BR>
<FORM ACTION="members.cgi" METHOD="POST">
<INPUT TYPE="hidden" NAME="user" VALUE="$INPUT{'user'}">
<INPUT TYPE="hidden" NAME="pass" VALUE="$INPUT{'pass'}">
<INPUT TYPE="hidden" NAME="a" VALUE="del_poll_com">
<INPUT TYPE=submit VALUE="Delete WebPoll">
</FORM></CENTER>
HTML
}

sub del_poll_com {

unlink("$data_path/$INPUT{'user'}.wpd");

&member_header;
print <<"HTML";
<CENTER><B>WebPoll deleted</B></CENTER>
HTML
}

sub add_post_img {
&member_header;
print <<"HTML";
<CENTER><B>Add Images to postcards</B><BR>
Please enter the URL of your images
<FORM ACTION="members.cgi" METHOD="POST">
Image 1 <INPUT TYPE="text" NAME="1" VALUE="http://"><BR>
Image 2 <INPUT TYPE="text" NAME="2" VALUE="http://"><BR>
Image 3 <INPUT TYPE="text" NAME="3" VALUE="http://"><BR>
Image 4 <INPUT TYPE="text" NAME="4" VALUE="http://"><BR>
Image 5 <INPUT TYPE="text" NAME="5" VALUE="http://"><BR>
You may add more images later by coming back to this page tho the main admin!<BR>
<INPUT TYPE="hidden" NAME="user" VALUE="$INPUT{'user'}">
<INPUT TYPE="hidden" NAME="pass" VALUE="$INPUT{'pass'}">
<INPUT TYPE="hidden" NAME="a" VALUE="add_post_img_com">
<INPUT TYPE=submit VALUE="Submit">
HTML
}

sub add_post_img_com {
&member_header;
print <<"HTML";
<CENTER><B>Images Saved</B></CENTER><BR>
HTML
open (DATA, "$data_path/$INPUT{'user'}.pci");
@data = <DATA>;
close DATA;
open(cnt, ">$data_path/$INPUT{'user'}.pci");
if ($INPUT{'1'} ne "http://") {
print cnt "$INPUT{'1'}\n";
}
if ($INPUT{'2'} ne "http://") {
print cnt "$INPUT{'2'}\n";
}
if ($INPUT{'3'} ne "http://") {
print cnt "$INPUT{'3'}\n";
}
if ($INPUT{'4'} ne "http://") {
print cnt "$INPUT{'4'}\n";
}
if ($INPUT{'5'} ne "http://") {
print cnt "$INPUT{'5'}\n";
}
foreach $line (@data) {
chomp ($line);
print cnt "$line\n";
}
close(cnt);
}

sub del_post_img {
$aa = "0";
&member_header;
print <<"HTML";
<FORM ACTION="members.cgi" METHOD="POST"><CENTER>
<TABLE BORDER CELLPADDING="2" ALIGN="Center">
<TR><TD COLSPAN=2>Delete Postcard Images</TD></TR>
HTML
open (DATA, "$data_path/$INPUT{'user'}.pci");
@data = <DATA>;
close DATA;
foreach $line (@data) {
$aa++;
chomp ($line);
print "<TR><TD><INPUT TYPE=\"radio\" NAME=\"num\" VALUE=\"$aa\"></TD><TD>$line</TD></TR>";
}
print <<"HTML";
<TR><TD COLSPAN=2>
<INPUT TYPE="hidden" NAME="user" VALUE="$INPUT{'user'}">
<INPUT TYPE="hidden" NAME="pass" VALUE="$INPUT{'pass'}">
<INPUT TYPE="hidden" NAME="a" VALUE="del_post_img_com">
<INPUT TYPE=submit NAME=submit VALUE="Delete"> &nbsp;
<INPUT TYPE=submit NAME=submit VALUE="Delete All"></TD>
</TR></TABLE></CENTER></FORM>
HTML
}

sub del_post_img_com {
if ($INPUT{'submit'} eq "Delete") {
$aa = "0";
open (DATA, "$data_path/$INPUT{'user'}.pci");
@data = <DATA>;
close DATA;
open(cnt, ">$data_path/$INPUT{'user'}.pci");
foreach $line (@data) {
$aa++;
if ($aa eq "$INPUT{'num'}") {
print cnt "";
}
else {
print cnt "$line";
}
}
close(cnt);
&member_header;
print <<"HTML";
<CENTER><B>Image Deleted</B></CENTER>
HTML
}
if ($INPUT{'submit'} eq "Delete All") {
unlink("$data_path/$INPUT{'user'}.pci");
&member_header;
print <<"HTML";
<CENTER><B>All images Deleted</B></CENTER>
HTML
}
}

sub post_code {
&member_header;
print <<"HTML";
<CENTER><TABLE BORDER CELLPADDING="2">
<TR><TD><P ALIGN=Center>
<BIG>PostCard code:</BIG></TD>
</TR><TR><TD><P ALIGN=Center>
Copy and paste this code into your pages html
<P ALIGN=Center>
<FONT COLOR="#ff0000"><SMALL>
&lt;Center&gt;&lt;A
HREF="$html_cgi_path/postcard.cgi?u=$INPUT{'user'}&amp;a=send"&gt;Send a
PostCard&lt;/A&gt;&lt;BR&gt;<BR>
&lt;A HREF="$html_cgi_path/postcard.cgi?u=$INPUT{'user'}&amp;a=pick"&gt;Pick
Up a Postcard&lt;/A&gt;&lt;/CENTER&gt;
</SMALL></FONT></TD>
</TR></TABLE></CENTER>
HTML
}

sub edit_post {
open (FILE, "$data_path/$INPUT{'user'}.pcc");
flock (FILE, 2);
$text = <FILE>;
chop ($text);
$link = <FILE>;
chop ($link);
$vlink = <FILE>;
chop ($vlink);
$bg = <FILE>;
chop ($bg);
$image = <FILE>;
chop ($image);
$heading = <FILE>;
chop ($heading);
flock (FILE, 8);
close(FILE);
if ($text eq "") { $text = "#000000"; }
if ($link eq "") { $link = "#0000ff"; }
if ($vlink eq "") { $vlink = "#ff8080"; }
if ($bg eq "") { $bg = "#ffffff"; }
if ($heading eq "") { $heading = "$name Postcards"; }

&member_header;
print <<"HTML";
<FORM ACTION="members.cgi" METHOD="POST">
<CENTER><TABLE BORDER CELLPADDING="2" ALIGN="Center">
<TR><TD COLSPAN=2><P ALIGN=Center>
<BIG>Edit Postcards</BIG></TD>
</TR><TR><TD>Text Color:</TD><TD>
<INPUT TYPE="text" NAME="text" VALUE="$text"></TD>
</TR><TR><TD>Link Color:</TD><TD>
<INPUT TYPE="text" NAME="link" VALUE="$link"></TD>
</TR><TR><TD>Visited Link Color:</TD><TD>
<INPUT TYPE="text" NAME="vlink" VALUE="$vlink"></TD>
</TR><TR><TD>BackGround color:</TD><TD>
<INPUT TYPE="text" NAME="bg" VALUE="$bg"></TD>
</TR><TR><TD>BackGround Image:</TD><TD>
<INPUT TYPE="text" NAME="image" VALUE="$image"></TD></TR>
<TR><TD>Heading:</TD><TD>
<INPUT TYPE="text" NAME="heading" VALUE="$heading"></TD>
</TR><TR><TD COLSPAN=2><P ALIGN=Center>
<INPUT TYPE="hidden" NAME="user" VALUE="$INPUT{'user'}">
<INPUT TYPE="hidden" NAME="pass" VALUE="$INPUT{'pass'}">
<INPUT TYPE="hidden" NAME="a" VALUE="edit_post_com">
<INPUT TYPE=submit VALUE="Update"></TD>
</TR></TABLE></CENTER></FORM>
HTML
}

sub edit_post_com {
open(cnt, ">$data_path/$INPUT{'user'}.pcc");
print cnt "$INPUT{'text'}\n";
print cnt "$INPUT{'link'}\n";
print cnt "$INPUT{'vlink'}\n";
print cnt "$INPUT{'bg'}\n";
print cnt "$INPUT{'image'}\n";
print cnt "$INPUT{'heading'}\n";
close(cnt);

&member_header;
print <<"HTML";
<CENTER><B>Postcards updated</B></CENTER>
HTML
}

sub email_form_code {
&member_header;
print <<"HTML";
<CENTER><TABLE BORDER CELLPADDING="2">
<TR><TD><P ALIGN=Center>
<BIG>Mailing list code:</BIG></TD>
</TR><TR><TD><P ALIGN=Center>
Copy and paste this code into your pages html<BR>
You may add as many fields as you want but you must keep ALL the felds in this code except the comments and name
<P ALIGN=Center>
<FONT COLOR="#ff0000"><SMALL>
&lt;FORM ACTION="$html_cgi_path/email.cgi" METHOD="POST"&gt;<BR>
&lt;CENTER&gt;&lt;TABLE BORDER CELLPADDING="2" ALIGN="Center"&gt;<BR>
&lt;TR&gt;&lt;TD COLSPAN=2&gt;&lt;P ALIGN=Center&gt;E-Mail
Me:&lt;/TD&gt;&lt;/TR&gt;<BR>
&lt;TR&gt;&lt;TD&gt;Your name:&lt;/TD&gt;<BR>
&lt;TD&gt;&lt;INPUT TYPE="text"
NAME="name"&gt;&lt;/TD&gt;&lt;/TR&gt;<BR>
&lt;TR&gt;&lt;TD&gt;Your E-Mail:&lt;/TD&gt;<BR>
&lt;TD&gt;&lt;INPUT TYPE="text"
NAME="email"&gt;&lt;/TD&gt;&lt;/TR&gt;<BR>
&lt;TR&gt;&lt;TD&gt;Comments:&lt;/TD&gt;<BR>
&lt;TD&gt;&lt;TEXTAREA NAME="comments"
COLS="18"&gt;&lt;/TEXTAREA&gt;&lt;/TD&gt;&lt;/TR&gt;<BR>
&lt;TR&gt;&lt;TD COLSPAN=2&gt;<BR>
&lt;CENTER&gt;&lt;INPUT TYPE="hidden" NAME="u" VALUE="$INPUT{'user'}"&gt;<BR>
&lt;INPUT TYPE="hidden" NAME="subject" VALUE="E-Mail from webpage"&gt;<BR>
&lt;INPUT TYPE="hidden" NAME="redir" VALUE="$url"&gt;<BR>
&lt;INPUT TYPE="hidden" NAME="to" VALUE="$mail"&gt;<BR>
&lt;INPUT TYPE=submit VALUE="Send E-Mail"&gt;&lt;/TD&gt;<BR>
&lt;/TR&gt;&lt;/TABLE&gt;&lt;/CENTER&gt;&lt;/FORM&gt;
</SMALL></FONT></TD>
</TR></TABLE></CENTER>
HTML
}

sub add_rand_img {
&member_header;
print <<"HTML";
<CENTER><B>Add Images to Random Image</B><BR>
Please enter the URL of your images
<FORM ACTION="members.cgi" METHOD="POST">
Image 1 <INPUT TYPE="text" NAME="1" VALUE="http://"><BR>
Image 2 <INPUT TYPE="text" NAME="2" VALUE="http://"><BR>
Image 3 <INPUT TYPE="text" NAME="3" VALUE="http://"><BR>
Image 4 <INPUT TYPE="text" NAME="4" VALUE="http://"><BR>
Image 5 <INPUT TYPE="text" NAME="5" VALUE="http://"><BR>
You may add more images later by coming back to this page tho the main admin!<BR>
<INPUT TYPE="hidden" NAME="user" VALUE="$INPUT{'user'}">
<INPUT TYPE="hidden" NAME="pass" VALUE="$INPUT{'pass'}">
<INPUT TYPE="hidden" NAME="a" VALUE="add_rand_img_com">
<INPUT TYPE=submit VALUE="Submit">
HTML
}

sub add_rand_img_com {
&member_header;
print <<"HTML";
<CENTER><B>Images Saved</B></CENTER><BR>
HTML
open (DATA, "$data_path/$INPUT{'user'}.rid");
@data = <DATA>;
close DATA;
open(cnt, ">$data_path/$INPUT{'user'}.rid");
if ($INPUT{'1'} ne "http://") {
print cnt "$INPUT{'1'}\n";
}
if ($INPUT{'2'} ne "http://") {
print cnt "$INPUT{'2'}\n";
}
if ($INPUT{'3'} ne "http://") {
print cnt "$INPUT{'3'}\n";
}
if ($INPUT{'4'} ne "http://") {
print cnt "$INPUT{'4'}\n";
}
if ($INPUT{'5'} ne "http://") {
print cnt "$INPUT{'5'}\n";
}
foreach $line (@data) {
chomp ($line);
print cnt "$line\n";
}
close(cnt);
}

sub del_rand_img {
$aa = "0";
&member_header;
print <<"HTML";
<FORM ACTION="members.cgi" METHOD="POST"><CENTER>
<TABLE BORDER CELLPADDING="2" ALIGN="Center">
<TR><TD COLSPAN=2>Delete Random Images</TD></TR>
HTML
open (DATA, "$data_path/$INPUT{'user'}.rid");
@data = <DATA>;
close DATA;
foreach $line (@data) {
$aa++;
chomp ($line);
print "<TR><TD><INPUT TYPE=\"radio\" NAME=\"num\" VALUE=\"$aa\"></TD><TD>$line</TD></TR>";
}
print <<"HTML";
<TR><TD COLSPAN=2>
<INPUT TYPE="hidden" NAME="user" VALUE="$INPUT{'user'}">
<INPUT TYPE="hidden" NAME="pass" VALUE="$INPUT{'pass'}">
<INPUT TYPE="hidden" NAME="a" VALUE="del_rand_img_com">
<INPUT TYPE=submit NAME=submit VALUE="Delete"> &nbsp;
<INPUT TYPE=submit NAME=submit VALUE="Delete All"></TD>
</TR></TABLE></CENTER></FORM>
HTML
}

sub del_rand_img_com {
if ($INPUT{'submit'} eq "Delete") {
$aa = "0";
open (DATA, "$data_path/$INPUT{'user'}.rid");
@data = <DATA>;
close DATA;
open(cnt, ">$data_path/$INPUT{'user'}.rid");
foreach $line (@data) {
$aa++;
if ($aa eq "$INPUT{'num'}") {
print cnt "";
}
else {
print cnt "$line";
}
}
close(cnt);
&member_header;
print <<"HTML";
<CENTER><B>Image Deleted</B></CENTER>
HTML
}
if ($INPUT{'submit'} eq "Delete All") {
unlink("$data_path/$INPUT{'user'}.rid");
&member_header;
print <<"HTML";
<CENTER><B>All images Deleted</B></CENTER>
HTML
}
}

sub rand_code {
&member_header;
print <<"HTML";
<CENTER><TABLE BORDER CELLPADDING="2">
<TR><TD><P ALIGN=Center>
<BIG>Random Image code:</BIG></TD>
</TR><TR><TD><P ALIGN=Center>
Copy and paste this code into your pages html
<P ALIGN=Center>
<FONT COLOR="#ff0000"><SMALL>
&lt;Center&gt;&lt;IMG SRC="$html_cgi_path/image.cgi?u=$INPUT{'user'}"&gt;&lt;/CENTER&gt;
</SMALL></FONT></TD>
</TR></TABLE></CENTER>
HTML
}

## Removeing this line will violate copyright laws!!
print "<CENTER><HR width=150><SMALL>Ran with <A HREF=http://perl.d0tt.com>REMOTE 2.0</A></SMALL></CENTER>";