#!/usr/bin/perl

####################################
##                                ##
##            REMOTE              ##
##  CopyRight Byron Chilton 2000  ##
##      http://www.d0tt.com       ##
##                                ##
##     DO NOT EDIT THIS FILE      ##
##                                ##
####################################

require "config.pl";

  read(STDIN, $buffer, $ENV{'CONTENT_LENGTH'});
  if (length($buffer) < 5) {
    $buffer = $ENV{QUERY_STRING};
  }
 
  @pairs = split(/&/, $buffer);
  foreach $pair (@pairs) {
    ($name, $value) = split(/=/, $pair);

    $value =~ tr/+/ /;
    $value =~ s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/eg;
    $value =~ s/[\;\|\\ ]/ /ig;
    $INPUT{$name} = $value;
}

print "Content-type: text/html\n\n";
if ($INPUT{'u'}) {
open (FILE, "$data_path/$INPUT{'u'}.mem");
flock (FILE, 2);
$name = <FILE>;
chop ($name);
$cryptpass = <FILE>;
chop ($cryptpass);
$mail = <FILE>;
chop ($mail);
$url = <FILE>;
chop ($url);
$site_title = <FILE>;
chop ($site_title);
flock (FILE, 8);
close(FILE);

open (FILE, "$data_path/$INPUT{'u'}.pcc");
flock (FILE, 2);
$text = <FILE>;
chop ($text);
$link = <FILE>;
chop ($link);
$vlink = <FILE>;
chop ($vlink);
$bg = <FILE>;
chop ($bg);
$image = <FILE>;
chop ($image);
$heading = <FILE>;
chop ($heading);
flock (FILE, 8);
close(FILE);

if ($name eq "") { 
&postheader;
print "<CENTER><B>Username Error!! The username $INPUT{'u'} was not found!!</B></CENTER>";
}
else {

if ($INPUT{'a'} eq "send") { &send_form }
elsif ($INPUT{'a'} eq "pick") { &pick_form }
elsif ($INPUT{'a'} eq "pick_up") { &pick_up }
elsif ($INPUT{'a'} eq "preview") { &pre_form }
elsif ($INPUT{'a'} eq "send_card") { &send_card }

else {
&postheader;
print "<CENTER><B>Command not entered!!</B></CENTER>";
}
}
}
else {
&postheader;
print "<CENTER><B>Username Error!! No username was entered!</B></CENTER>";
}

sub send_form {
&postheader;
print <<"HTML";
<FORM ACTION="postcard.cgi" METHOD="POST">
<CENTER><TABLE BORDER CELLPADDING="2" ALIGN="Center"><TR>
<TD COLSPAN=2><P ALIGN=Center>
<BIG>Send a postcard</BIG></TD>
</TR><TR><TD>Your Name:</TD><TD>
<INPUT TYPE="text" NAME="yname"></TD></TR>
<TR><TD>There Name:</TD><TD>
<INPUT TYPE="text" NAME="tname"></TD>
</TR><TR><TD>Your E-Mail:</TD><TD>
<INPUT TYPE="text" NAME="yemail"></TD>
</TR><TR><TD>There E-Mail:</TD>
<TD><INPUT TYPE="text" NAME="temail"></TD></TR><TR><TD>Heading:</TD><TD>
<INPUT TYPE="text" NAME="head"></TD>
</TR><TR><TD>Message:</TD><TD>
<INPUT TYPE="text" NAME="mess"></TD>
</TR><TR><TD>Text Color:</TD>
<TD><TABLE BORDER CELLPADDING="2"><TR>
<TD BGCOLOR=#000000>
<INPUT TYPE="radio" NAME="text" VALUE="#000000" CHECKED></TD>
<TD BGCOLOR=#000000><FONT COLOR="#c0c0c0">Black</FONT></TD>
<TD BGCOLOR=#ff0000>
<INPUT TYPE="radio" NAME="text" VALUE="#ff0000"></TD>
<TD BGCOLOR=#ff0000>Red</TD>
<TD BGCOLOR=#00ff00>
<INPUT TYPE="radio" NAME="text" VALUE="#00ff00"></TD>
<TD BGCOLOR=#00ff00>Green</TD>
</TR><TR><TD BGCOLOR=#ffffff>
<INPUT TYPE="radio" NAME="text" VALUE="#ffffff"></TD>
<TD BGCOLOR=#ffffff>White</TD>
<TD BGCOLOR=#0000ff>
<INPUT TYPE="radio" NAME="text" VALUE="#0000ff"></TD>
<TD BGCOLOR=#0000ff>Blue</TD>
<TD BGCOLOR=#ffff00>
<INPUT TYPE="radio" NAME="text" VALUE="#ffff00"></TD>
<TD BGCOLOR=#ffff00>Yellow</TD>
</TR></TABLE></TD></TR><TR><TD>BackGround Color:</TD>
<TD><TABLE BORDER CELLPADDING="2"><TR>
<TD BGCOLOR=#000000>
<INPUT TYPE="radio" NAME="bg" VALUE="#000000"></TD>
<TD BGCOLOR=#000000><FONT COLOR="#c0c0c0">Black</FONT></TD>
<TD BGCOLOR=#ff0000>
<INPUT TYPE="radio" NAME="bg" VALUE="#ff0000"></TD>
<TD BGCOLOR=#ff0000>Red</TD>
<TD BGCOLOR=#00ff00>
<INPUT TYPE="radio" NAME="bg" VALUE="#00ff00"></TD>
<TD BGCOLOR=#00ff00>Green</TD>
</TR><TR><TD BGCOLOR=#ffffff>
<INPUT TYPE="radio" NAME="bg" VALUE="#ffffff" CHECKED></TD>
<TD BGCOLOR=#ffffff>White</TD>
<TD BGCOLOR=#0000ff>
<INPUT TYPE="radio" NAME="bg" VALUE="#0000ff"></TD>
<TD BGCOLOR=#0000ff>Blue</TD>
<TD BGCOLOR=#ffff00>
<INPUT TYPE="radio" NAME="bg" VALUE="#ffff00"></TD>
<TD BGCOLOR=#ffff00>Yellow</TD>
</TR></TABLE></TD></TR><TR><TD>Link Color:</TD>
<TD><TABLE BORDER CELLPADDING="2">
<TR><TD BGCOLOR=#000000>
<INPUT TYPE="radio" NAME="link" VALUE="#000000"></TD>
<TD BGCOLOR=#000000><FONT COLOR="#c0c0c0">Black</FONT></TD>
<TD BGCOLOR=#ff0000>
<INPUT TYPE="radio" NAME="link" VALUE="#ff0000"></TD>
<TD BGCOLOR=#ff0000>Red</TD>
<TD BGCOLOR=#00ff00>
<INPUT TYPE="radio" NAME="link" VALUE="#00ff00"></TD>
<TD BGCOLOR=#00ff00>Green</TD>
</TR><TR><TD BGCOLOR=#ffffff>
<INPUT TYPE="radio" NAME="link" VALUE="#ffffff"></TD>
<TD BGCOLOR=#ffffff>White</TD>
<TD BGCOLOR=#0000ff>
<INPUT TYPE="radio" NAME="link" VALUE="#0000ff" CHECKED></TD>
<TD BGCOLOR=#0000ff>Blue</TD>
<TD BGCOLOR=#ffff00>
<INPUT TYPE="radio" NAME="link" VALUE="#ffff00"></TD>
<TD BGCOLOR=#ffff00>Yellow</TD>
</TR></TABLE>
</TD></TR><TR><TD COLSPAN=2><P ALIGN=Center>Image:</TD></TR><TR><TD COLSPAN=2>
<CENTER><TABLE BORDER CELLPADDING="2" ALIGN="Center">
HTML

open (DATA, "$data_path/$INPUT{'u'}.pci");
@data = <DATA>;
close DATA;
foreach $line (@data) {
chomp ($line);
print "<TR><TD><INPUT TYPE=\"radio\" NAME=\"num\" VALUE=\"$line\"></TD><TD><IMG SRC=\"$line\"></TD></TR>";
}

print <<"HTML";
</TABLE></TD></TR><TR>
<TD COLSPAN=2><P ALIGN=Center>
<INPUT TYPE="hidden" NAME="u" VALUE="$INPUT{'u'}">
<INPUT TYPE="hidden" NAME="a" VALUE="preview">
<INPUT TYPE=submit VALUE="preview"></TD>
</TR></TABLE></CENTER></FORM>
HTML
}

sub pre_form {
print <<"HTML";
<BODY BGCOLOR="$INPUT{'bg'}" TEXT="$INPUT{'text'}" LINK="$INPUT{'link'}" VLINK="$INPUT{'link'}">
<CENTER><TABLE BORDER CELLPADDING="2" ALIGN="Center">
<TR><TD COLSPAN=2><P ALIGN=Center>
$INPUT{'head'}</TD></TR><TR><TD COLSPAN=2><P ALIGN=Center>
<IMG SRC="$INPUT{'img'}"></TD></TR><TR>
<TD COLSPAN=2><P ALIGN=Center>
$INPUT{'mess'}</TD></TR><TR>
<TD><P ALIGN=Center>
To:</TD>
<TD><P ALIGN=Center>
From:</TD></TR><TR>
<TD><A HREF="mailto\:$INPUT{'temail'}">$INPUT{'tname'}</A></TD>
<TD><A HREF="mailto\:$INPUT{'yemail'}">$INPUT{'yname'}</A></TD>
</TR></TABLE>
<P>
<FORM ACTION="postcard.cgi" METHOD="POST">
<INPUT TYPE="hidden" NAME="tname" VALUE="$INPUT{'tname'}">
<INPUT TYPE="hidden" NAME="yname" VALUE="$INPUT{'yname'}">
<INPUT TYPE="hidden" NAME="temail" VALUE="$INPUT{'temail'}">
<INPUT TYPE="hidden" NAME="yemail" VALUE="$INPUT{'yemail'}">
<INPUT TYPE="hidden" NAME="mess" VALUE="$INPUT{'mess'}">
<INPUT TYPE="hidden" NAME="head" VALUE="$INPUT{'head'}">
<INPUT TYPE="hidden" NAME="img" VALUE="$INPUT{'num'}">
<INPUT TYPE="hidden" NAME="bg" VALUE="$INPUT{'bg'}">
<INPUT TYPE="hidden" NAME="text" VALUE="$INPUT{'text'}">
<INPUT TYPE="hidden" NAME="link" VALUE="$INPUT{'link'}">
  <INPUT TYPE="hidden" NAME="u" VALUE="$INPUT{'u'}">
  <INPUT TYPE="hidden" NAME="a" VALUE="send_card">
  <INPUT TYPE=submit VALUE="Send Card">
</FORM>
</CENTER>
HTML
}

sub send_card {
$card = crypt($INPUT{'temail'}, "aa");

open(cnt, ">$postcard_path/$card");
print cnt "$INPUT{'temail'}\n";
print cnt "$INPUT{'yemail'}\n";
print cnt "$INPUT{'tname'}\n";
print cnt "$INPUT{'yname'}\n";
print cnt "$INPUT{'mess'}\n";
print cnt "$INPUT{'head'}\n";
print cnt "$INPUT{'img'}\n";
print cnt "$INPUT{'bg'}\n";
print cnt "$INPUT{'text'}\n";
print cnt "$INPUT{'link'}\n";
close(cnt);

open (MAIL, "| $mailprog -t -oi") || die "Can't open $mailprog";
print MAIL "To: $INPUT{'temail'}\n";
print MAIL "Reply-to: $INPUT{'yemail'}\n";
print MAIL "From: $INPUT{'email'}\n";
print MAIL "Subject: You have recived a postcard\n";
print MAIL "You have recived a postcard from $INPUT{'yname'}\n\n";
print MAIL "To pick your postcard up go to:\n";
print MAIL "$html_cgi_path/postcard.cgi?a=pick_up&ticket=$card&u=$INPUT{'u'}\n\n\n";
print MAIL "$INPUT{'yname'}\n";

&postheader;
print <<"HTML";
<CENTER><B>Your postcard has been sent</B><BR>
The cards ticket number is <B>$card</B><BR>
If for some reason $INPUT{'tname'}<BR>
dosent recive there card it can be picked up at<BR>
$html_cgi_path/postcard.cgi?a=pick&u=$INPUT{'u'}
HTML
}

sub pick_up {
open (FILE, "$postcard_path/$INPUT{'ticket'}");
flock (FILE, 2);
$temail = <FILE>;
chop ($temail);
$yemail = <FILE>;
chop ($yemail);
$tname = <FILE>;
chop ($tname);
$yname = <FILE>;
chop ($yname);
$mess = <FILE>;
chop ($mess);
$head = <FILE>;
chop ($head);
$img = <FILE>;
chop ($img);
$bg = <FILE>;
chop ($bg);
$text = <FILE>;
chop ($text);
$link = <FILE>;
chop ($link);
flock (FILE, 8);
close(FILE);

if ($temail eq "") {
&postheader;
print "<CENTER><B>Sorry your postcard could not be found!!</B></CENTER>";
}
else {
print <<"HTML";
<BODY BGCOLOR="$bg" TEXT="$text" LINK="$link" VLINK="$link">
<CENTER><TABLE BORDER CELLPADDING="2" ALIGN="Center">
<TR><TD COLSPAN=2><P ALIGN=Center>
$head</TD></TR><TR><TD COLSPAN=2><P ALIGN=Center>
<IMG SRC="$img"></TD></TR><TR>
<TD COLSPAN=2><P ALIGN=Center>
$mess</TD></TR><TR>
<TD><P ALIGN=Center>
To:</TD>
<TD><P ALIGN=Center>
From:</TD></TR><TR>
<TD><A HREF="mailto\:$temail">$tname</A></TD>
<TD><A HREF="mailto\:$yemail">$yname</A></TD>
</TR></TABLE>
<P>
This postcard had been deleted to save space on our server!<BR>
<P>
<P>
To send your own postcard go to:<BR>
$html_cgi_path/postcard.cgi?a=send&u=$INPUT{'u'}
HTML
unlink("$postcard_path/$INPUT{'ticket'}");
}
}

sub pick_form {
&postheader;
print <<"HTML";
<FORM ACTION="postcard.cgi" METHOD="POST">
  <P ALIGN=Center>
Card Number:<BR>
  <INPUT TYPE="hidden" NAME="u" VALUE="$INPUT{'u'}">
  <INPUT TYPE="hidden" NAME="a" VALUE="pick_up">
  <INPUT TYPE="text" NAME="ticket">
  <INPUT TYPE=submit VALUE="View Card">
</FORM>
HTML
}


&postfooter;