#!/usr/bin/perl

####################################
##                                ##
##            REMOTE              ##
##  CopyRight Byron Chilton 2000  ##
##      http://www.d0tt.com       ##
##                                ##
##     DO NOT EDIT THIS FILE      ##
##                                ##
####################################

require "config.pl";

  read(STDIN, $buffer, $ENV{'CONTENT_LENGTH'});
  if (length($buffer) < 5) {
    $buffer = $ENV{QUERY_STRING};
  }
 
  @pairs = split(/&/, $buffer);
  foreach $pair (@pairs) {
    ($name, $value) = split(/=/, $pair);

    $value =~ tr/+/ /;
    $value =~ s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/eg;
    $value =~ s/[\;\|\\ ]/ /ig;
    $INPUT{$name} = $value;
}
print "Content-type: text/html\n\n";
if ($INPUT{'user'}) {
open (FILE, "$data_path/$INPUT{'user'}.mem");
flock (FILE, 2);
$name = <FILE>;
chop ($name);
$cryptpass = <FILE>;
chop ($cryptpass);
$mail = <FILE>;
chop ($mail);
$url = <FILE>;
chop ($url);
$site_title = <FILE>;
chop ($site_title);
flock (FILE, 8);
close(FILE);

if ($name eq "") { 
&mlheader;
print "<CENTER><B>Username Error!! The username $INPUT{'user'} was not found!!</B></CENTER>";
&mlfooter;
}
else {
if ($INPUT{'a'} eq "sub") { &add_mail; }
elsif ($INPUT{'a'} eq "rev") { &delete_mail; }

sub delete_mail {
$fnd = "0";
open (DATA, "$data_path/$INPUT{'user'}.mld");
@data = <DATA>;
close DATA;
open(DATA, ">$data_path/$INPUT{'user'}.mld");
foreach $line (@data) {
chomp ($line);
$L = "$line";
if ($L eq "$INPUT{'email'}") {
print DATA "";
$fnd = "1";
}
else {
print DATA "$line\n";
}
}
close DATA;
if ($fnd eq "0") {
&mlheader;
print "<CENTER><B>Sorry, The E-Mail addres $INPUT{'email'} was not found</B></CENTER>";
&mlfooter;
}
else {
&mlheader;
print <<"HTML";
<CENTER><B>The E-Mail address $INPUT{'email'} was deleted</B></CENTER>
HTML
&mlfooter;
}
}

sub add_mail {
$fnd = "0";
open (DATA, "$data_path/$INPUT{'user'}.mld");
@data = <DATA>;
close DATA;
foreach $line (@data) {
chomp ($line);
$L = "$line";
if ($L eq "$INPUT{'email'}") {
$fnd = "1";
}
}
if ($fnd eq "1") {
&mlheader;
print "<CENTER><B>The E-Mail address $INPUT{'email'} is allready on list</B></CENTER>";
&mlfooter;
}
else {
open (DATA, "$data_path/$INPUT{'user'}.mld");
@data = <DATA>;
close DATA;
open(DATA, ">$data_path/$INPUT{'user'}.mld");
print DATA "$INPUT{'email'}\n";
foreach $line (@data) {
chomp ($line);
print DATA "$line\n";
}
&mlheader;
print "<CENTER><B>The E-Mail address $INPUT{'email'} was Added</B></CENTER>";
&mlfooter;
}
}


}
}
else {
&mlheader;
print "<CENTER><B>Username Error!! No username Entered!!</B></CENTER>";
&mlfooter;
}